// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Twilio.OpenApiClient.Models;
using Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Item;
using Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usecases;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p
{
    /// <summary>
    /// A service for (fetch/create/delete) A2P Campaign for a Messaging Service
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Usa2pRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Messaging Service Use Case resource. Fetch possible use cases for service. The Use Cases API returns an empty list if there is an issue with the customer&apos;s A2P brand registration. This Brand cannot register any campaign use cases. Customers are requested to contact support with their A2P brand information.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usecases.UsecasesRequestBuilder Usecases
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usecases.UsecasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>A service for (fetch/create/delete) A2P Campaign for a Messaging Service</summary>
        /// <param name="position">The SID of the US A2P Compliance resource to delete `QE2c6890da8086d771620e9b13fadeba0b`.</param>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Item.WithSItemRequestBuilder"/></returns>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Item.WithSItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("Sid", position);
                return new global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Item.WithSItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Usa2pRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_messaging_v1/v1/Services/{MessagingServiceS%2Did}/Compliance/Usa2p{?Page*,PageSize*,PageToken*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Usa2pRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_messaging_v1/v1/Services/{MessagingServiceS%2Did}/Compliance/Usa2p{?Page*,PageSize*,PageToken*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_messaging_v1_ListUsAppToPerson_200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_messaging_v1_ListUsAppToPerson_200?> GetAsync(Action<RequestConfiguration<global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder.Usa2pRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_messaging_v1_ListUsAppToPerson_200> GetAsync(Action<RequestConfiguration<global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder.Usa2pRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_messaging_v1_ListUsAppToPerson_200>(requestInfo, global::Soenneker.Twilio.OpenApiClient.Models.Twilio_messaging_v1_ListUsAppToPerson_200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Messaging_v1_service_us_app_to_person_response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Twilio.OpenApiClient.Models.Messaging_v1_service_us_app_to_person_response?> PostAsync(global::Soenneker.Twilio.OpenApiClient.Models.Twilio_messaging_v1_CreateUsAppToPerson body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Twilio.OpenApiClient.Models.Messaging_v1_service_us_app_to_person_response> PostAsync(global::Soenneker.Twilio.OpenApiClient.Models.Twilio_messaging_v1_CreateUsAppToPerson body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Twilio.OpenApiClient.Models.Messaging_v1_service_us_app_to_person_response>(requestInfo, global::Soenneker.Twilio.OpenApiClient.Models.Messaging_v1_service_us_app_to_person_response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder.Usa2pRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder.Usa2pRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Twilio.OpenApiClient.Models.Twilio_messaging_v1_CreateUsAppToPerson body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Twilio.OpenApiClient.Models.Twilio_messaging_v1_CreateUsAppToPerson body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/x-www-form-urlencoded", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class Usa2pRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            /// <summary>The page index. This value is simply for client state.</summary>
            public int? Page { get; set; }
            /// <summary>How many resources to return in each list page. The default is 50, and the maximum is 1000.</summary>
            public long? PageSize { get; set; }
            /// <summary>The page token. This is provided by the API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? PageToken { get; set; }
#nullable restore
#else
            public string PageToken { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Usa2pRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Twilio.OpenApiClient.Twilio_messaging_v1.V1.Services.Item.Compliance.Usa2p.Usa2pRequestBuilder.Usa2pRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Usa2pRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
