// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Twilio.OpenApiClient.Twilio_accounts_v1.V1.Messaging.GeoPermissions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Twilio.OpenApiClient.Twilio_accounts_v1.V1.Messaging
{
    /// <summary>
    /// Builds and executes requests for operations under \twilio_accounts_v1\v1\Messaging
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessagingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Manage Geo Permissions for each country.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_accounts_v1.V1.Messaging.GeoPermissions.GeoPermissionsRequestBuilder GeoPermissions
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_accounts_v1.V1.Messaging.GeoPermissions.GeoPermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_accounts_v1.V1.Messaging.MessagingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_accounts_v1/v1/Messaging", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_accounts_v1.V1.Messaging.MessagingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_accounts_v1/v1/Messaging", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
