// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Twilio_numbers_v2.V2.RegulatoryCompliance.Bundles
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetEndUserTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "business")]
        #pragma warning disable CS1591
        Business,
        #pragma warning restore CS1591
        [EnumMember(Value = "individual")]
        #pragma warning disable CS1591
        Individual,
        #pragma warning restore CS1591
    }
}
