// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Twilio.OpenApiClient.Twilio_conversations_v2.V2.ControlPlane.Operations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Twilio.OpenApiClient.Twilio_conversations_v2.V2.ControlPlane.Operations
{
    /// <summary>
    /// Builds and executes requests for operations under \twilio_conversations_v2\v2\ControlPlane\Operations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OperationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Twilio.OpenApiClient.twilio_conversations_v2.v2.ControlPlane.Operations.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_conversations_v2.V2.ControlPlane.Operations.Item.OperationsItemRequestBuilder"/></returns>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_conversations_v2.V2.ControlPlane.Operations.Item.OperationsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Twilio.OpenApiClient.Twilio_conversations_v2.V2.ControlPlane.Operations.Item.OperationsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_conversations_v2.V2.ControlPlane.Operations.OperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OperationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_conversations_v2/v2/ControlPlane/Operations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_conversations_v2.V2.ControlPlane.Operations.OperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OperationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_conversations_v2/v2/ControlPlane/Operations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
