// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Twilio.OpenApiClient.Twilio_pricing_v1.V1.Voice.Countries;
using Soenneker.Twilio.OpenApiClient.Twilio_pricing_v1.V1.Voice.Numbers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Twilio.OpenApiClient.Twilio_pricing_v1.V1.Voice
{
    /// <summary>
    /// Builds and executes requests for operations under \twilio_pricing_v1\v1\Voice
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VoiceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Voice pricing by country</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_pricing_v1.V1.Voice.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_pricing_v1.V1.Voice.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Numbers property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_pricing_v1.V1.Voice.Numbers.NumbersRequestBuilder Numbers
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_pricing_v1.V1.Voice.Numbers.NumbersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_pricing_v1.V1.Voice.VoiceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VoiceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_pricing_v1/v1/Voice", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_pricing_v1.V1.Voice.VoiceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VoiceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_pricing_v1/v1/Voice", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
