// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Twilio.OpenApiClient.Twilio_routes_v2.V2.Trunks.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Twilio.OpenApiClient.Twilio_routes_v2.V2.Trunks
{
    /// <summary>
    /// Builds and executes requests for operations under \twilio_routes_v2\v2\Trunks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrunksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Twilio.OpenApiClient.twilio_routes_v2.v2.Trunks.item collection</summary>
        /// <param name="position">The absolute URL of the SIP Trunk</param>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_routes_v2.V2.Trunks.Item.WithSipTrunkDomainItemRequestBuilder"/></returns>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_routes_v2.V2.Trunks.Item.WithSipTrunkDomainItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("SipTrunkDomain", position);
                return new global::Soenneker.Twilio.OpenApiClient.Twilio_routes_v2.V2.Trunks.Item.WithSipTrunkDomainItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_routes_v2.V2.Trunks.TrunksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrunksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_routes_v2/v2/Trunks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_routes_v2.V2.Trunks.TrunksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrunksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_routes_v2/v2/Trunks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
