// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Twilio.OpenApiClient.Twilio_lookups_v1.V1.PhoneNumbers.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Twilio.OpenApiClient.Twilio_lookups_v1.V1.PhoneNumbers
{
    /// <summary>
    /// Builds and executes requests for operations under \twilio_lookups_v1\v1\PhoneNumbers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneNumbersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Detailed information on phone numbers</summary>
        /// <param name="position">The phone number to lookup in [E.164](https://www.twilio.com/docs/glossary/what-e164) format, which consists of a + followed by the country code and subscriber number.</param>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_lookups_v1.V1.PhoneNumbers.Item.WithPhoneNumberItemRequestBuilder"/></returns>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_lookups_v1.V1.PhoneNumbers.Item.WithPhoneNumberItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("PhoneNumber", position);
                return new global::Soenneker.Twilio.OpenApiClient.Twilio_lookups_v1.V1.PhoneNumbers.Item.WithPhoneNumberItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_lookups_v1.V1.PhoneNumbers.PhoneNumbersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhoneNumbersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_lookups_v1/v1/PhoneNumbers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_lookups_v1.V1.PhoneNumbers.PhoneNumbersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhoneNumbersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_lookups_v1/v1/PhoneNumbers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
