// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Twilio.OpenApiClient.Twilio_trusthub_v1.V1.ComplianceInquiries.Registration.Item.RegulatoryCompliance.GB.Initialize;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Twilio.OpenApiClient.Twilio_trusthub_v1.V1.ComplianceInquiries.Registration.Item.RegulatoryCompliance.GB
{
    /// <summary>
    /// Builds and executes requests for operations under \twilio_trusthub_v1\v1\ComplianceInquiries\Registration\{RegistrationId}\RegulatoryCompliance\GB
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GBRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Initialize property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_trusthub_v1.V1.ComplianceInquiries.Registration.Item.RegulatoryCompliance.GB.Initialize.InitializeRequestBuilder Initialize
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_trusthub_v1.V1.ComplianceInquiries.Registration.Item.RegulatoryCompliance.GB.Initialize.InitializeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_trusthub_v1.V1.ComplianceInquiries.Registration.Item.RegulatoryCompliance.GB.GBRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GBRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_trusthub_v1/v1/ComplianceInquiries/Registration/{RegistrationId}/RegulatoryCompliance/GB", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_trusthub_v1.V1.ComplianceInquiries.Registration.Item.RegulatoryCompliance.GB.GBRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GBRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_trusthub_v1/v1/ComplianceInquiries/Registration/{RegistrationId}/RegulatoryCompliance/GB", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
