// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.ESimProfiles;
using Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.Fleets;
using Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.IpCommands;
using Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.NetworkAccessProfiles;
using Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.Networks;
using Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.SettingsUpdates;
using Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.Sims;
using Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.SmsCommands;
using Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.UsageRecords;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \twilio_supersim_v1\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>eSIM Profiles that can be loaded onto consumer eUICC SIMs</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.ESimProfiles.ESimProfilesRequestBuilder ESimProfiles
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.ESimProfiles.ESimProfilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Configure shared settings inherited by all Super SIMs assigned to the Fleet</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.Fleets.FleetsRequestBuilder Fleets
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.Fleets.FleetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Machine-to-machine IP Commands sent to/from Super SIMs</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.IpCommands.IpCommandsRequestBuilder IpCommands
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.IpCommands.IpCommandsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The NetworkAccessProfiles property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.NetworkAccessProfiles.NetworkAccessProfilesRequestBuilder NetworkAccessProfiles
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.NetworkAccessProfiles.NetworkAccessProfilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Mobile operator networks to which Super SIMs can connect</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.Networks.NetworksRequestBuilder Networks
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.Networks.NetworksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SettingsUpdates property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.SettingsUpdates.SettingsUpdatesRequestBuilder SettingsUpdates
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.SettingsUpdates.SettingsUpdatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Individual IoT Super SIMs</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.Sims.SimsRequestBuilder Sims
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.Sims.SimsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Machine-to-machine SMS Commands sent to/from SIMs</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.SmsCommands.SmsCommandsRequestBuilder SmsCommands
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.SmsCommands.SmsCommandsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Usage information for Sim resources</summary>
        public global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.UsageRecords.UsageRecordsRequestBuilder UsageRecords
        {
            get => new global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.UsageRecords.UsageRecordsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_supersim_v1/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Twilio_supersim_v1.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twilio_supersim_v1/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
