// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>How to summarize the usage by time. Can be: `daily`, `hourly`, or `all`. A value of `all` returns one Usage Record that describes the usage for the entire period.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AccountUsageRecordEnumGranularity
    {
        [EnumMember(Value = "hourly")]
        #pragma warning disable CS1591
        Hourly,
        #pragma warning restore CS1591
        [EnumMember(Value = "daily")]
        #pragma warning disable CS1591
        Daily,
        #pragma warning restore CS1591
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
