// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>The status of the sender.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChannelsSenderEnumStatus
    {
        [EnumMember(Value = "CREATING")]
        #pragma warning disable CS1591
        Creating,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONLINE")]
        #pragma warning disable CS1591
        Online,
        #pragma warning restore CS1591
        [EnumMember(Value = "OFFLINE")]
        #pragma warning disable CS1591
        Offline,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_VERIFICATION")]
        #pragma warning disable CS1591
        PendingVerification,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERIFYING")]
        #pragma warning disable CS1591
        Verifying,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONLINE:UPDATING")]
        #pragma warning disable CS1591
        ONLINEColonUPDATING,
        #pragma warning restore CS1591
        [EnumMember(Value = "TWILIO_REVIEW")]
        #pragma warning disable CS1591
        TwilioReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "DRAFT")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "STUBBED")]
        #pragma warning disable CS1591
        Stubbed,
        #pragma warning restore CS1591
    }
}
