// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Chat_v3_channel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Channel resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSid { get; set; }
#nullable restore
#else
        public string AccountSid { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The JSON string that stores application-specific data. If attributes have not been set, `{}` is returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Attributes { get; set; }
#nullable restore
#else
        public string Attributes { get; set; }
#endif
        /// <summary>The `identity` of the User that created the channel. If the Channel was created by using the API, the value is `system`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The string that you assigned to describe the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>The number of Members in the Channel.</summary>
        public int? MembersCount { get; set; }
        /// <summary>The number of Messages that have been passed in the Channel.</summary>
        public int? MessagesCount { get; set; }
        /// <summary>The unique ID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) this channel belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessagingServiceSid { get; set; }
#nullable restore
#else
        public string MessagingServiceSid { get; set; }
#endif
        /// <summary>The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the Channel resource is associated with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceSid { get; set; }
#nullable restore
#else
        public string ServiceSid { get; set; }
#endif
        /// <summary>The unique string that we created to identify the Channel resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sid { get; set; }
#nullable restore
#else
        public string Sid { get; set; }
#endif
        /// <summary>&quot;The visibility of the channel. Can be: `public` or `private`.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_chat_v3_channel_enum_channel_type? Type { get; set; }
        /// <summary>An application-defined string that uniquely identifies the resource. It can be used to address the resource in place of the resource&apos;s `sid` in the URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UniqueName { get; set; }
#nullable restore
#else
        public string UniqueName { get; set; }
#endif
        /// <summary>The absolute URL of the Channel resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Chat_v3_channel"/> and sets the default values.
        /// </summary>
        public Chat_v3_channel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Chat_v3_channel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Chat_v3_channel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Chat_v3_channel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_sid", n => { AccountSid = n.GetStringValue(); } },
                { "attributes", n => { Attributes = n.GetStringValue(); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "friendly_name", n => { FriendlyName = n.GetStringValue(); } },
                { "members_count", n => { MembersCount = n.GetIntValue(); } },
                { "messages_count", n => { MessagesCount = n.GetIntValue(); } },
                { "messaging_service_sid", n => { MessagingServiceSid = n.GetStringValue(); } },
                { "service_sid", n => { ServiceSid = n.GetStringValue(); } },
                { "sid", n => { Sid = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_chat_v3_channel_enum_channel_type>(); } },
                { "unique_name", n => { UniqueName = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_sid", AccountSid);
            writer.WriteStringValue("attributes", Attributes);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteStringValue("friendly_name", FriendlyName);
            writer.WriteIntValue("members_count", MembersCount);
            writer.WriteIntValue("messages_count", MessagesCount);
            writer.WriteStringValue("messaging_service_sid", MessagingServiceSid);
            writer.WriteStringValue("service_sid", ServiceSid);
            writer.WriteStringValue("sid", Sid);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_chat_v3_channel_enum_channel_type>("type", Type);
            writer.WriteStringValue("unique_name", UniqueName);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
