// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>Lifecycle status of an Action.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConversationsV2ActionStatus
    {
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
