// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>
    /// Transcription metadata.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConversationsV2ContentTranscriptionTranscription : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Audio channel identifier (0 for inbound, 1 for outbound).</summary>
        public int? Channel { get; set; }
        /// <summary>Overall confidence score for the transcription (0.0-1.0).</summary>
        public float? Confidence { get; set; }
        /// <summary>Transcription engine used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Engine { get; set; }
#nullable restore
#else
        public string Engine { get; set; }
#endif
        /// <summary>Word-level transcription data with timing information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ContentTranscriptionTranscription_words>? Words { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ContentTranscriptionTranscription_words> Words { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ContentTranscriptionTranscription"/> and sets the default values.
        /// </summary>
        public ConversationsV2ContentTranscriptionTranscription()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ContentTranscriptionTranscription"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ContentTranscriptionTranscription CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ContentTranscriptionTranscription();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channel", n => { Channel = n.GetIntValue(); } },
                { "confidence", n => { Confidence = n.GetFloatValue(); } },
                { "engine", n => { Engine = n.GetStringValue(); } },
                { "words", n => { Words = n.GetCollectionOfObjectValues<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ContentTranscriptionTranscription_words>(global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ContentTranscriptionTranscription_words.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("channel", Channel);
            writer.WriteFloatValue("confidence", Confidence);
            writer.WriteStringValue("engine", Engine);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ContentTranscriptionTranscription_words>("words", Words);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
