// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>Content type discriminator.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConversationsV2ContentText_type
    {
        [EnumMember(Value = "TEXT")]
        #pragma warning disable CS1591
        TEXT,
        #pragma warning restore CS1591
    }
}
