// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateShortCodeApplicationResponseSmsCampaignDetailsScUseCaseCategoriesItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TWO_FACTOR_AUTHENTICATION")]
        #pragma warning disable CS1591
        TwoFactorAuthentication,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNT_NOTIFICATIONS")]
        #pragma warning disable CS1591
        AccountNotifications,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOMER_CARE")]
        #pragma warning disable CS1591
        CustomerCare,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHARITY_NONPROFIT")]
        #pragma warning disable CS1591
        CharityNonprofit,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELIVERY_NOTIFICATIONS")]
        #pragma warning disable CS1591
        DeliveryNotifications,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_ALERT_MESSAGING")]
        #pragma warning disable CS1591
        FraudAlertMessaging,
        #pragma warning restore CS1591
        [EnumMember(Value = "EVENTS")]
        #pragma warning disable CS1591
        Events,
        #pragma warning restore CS1591
        [EnumMember(Value = "HIGHER_EDUCATION")]
        #pragma warning disable CS1591
        HigherEducation,
        #pragma warning restore CS1591
        [EnumMember(Value = "K12")]
        #pragma warning disable CS1591
        K12,
        #pragma warning restore CS1591
        [EnumMember(Value = "MARKETING")]
        #pragma warning disable CS1591
        Marketing,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLLING_AND_VOTING_NON_POLITICAL")]
        #pragma warning disable CS1591
        PollingAndVotingNonPolitical,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_ELECTION_CAMPAIGNS")]
        #pragma warning disable CS1591
        PoliticalElectionCampaigns,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUBLIC_SERVICE_ANNOUNCEMENT")]
        #pragma warning disable CS1591
        PublicServiceAnnouncement,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECURITY_ALERT")]
        #pragma warning disable CS1591
        SecurityAlert,
        #pragma warning restore CS1591
    }
}
