// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateShortCodeApplicationResponse_sms_campaign_details_sc_use_case_categories
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TWO_FACTOR_AUTHENTICATION")]
        #pragma warning disable CS1591
        TWO_FACTOR_AUTHENTICATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNT_NOTIFICATIONS")]
        #pragma warning disable CS1591
        ACCOUNT_NOTIFICATIONS,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOMER_CARE")]
        #pragma warning disable CS1591
        CUSTOMER_CARE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHARITY_NONPROFIT")]
        #pragma warning disable CS1591
        CHARITY_NONPROFIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELIVERY_NOTIFICATIONS")]
        #pragma warning disable CS1591
        DELIVERY_NOTIFICATIONS,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_ALERT_MESSAGING")]
        #pragma warning disable CS1591
        FRAUD_ALERT_MESSAGING,
        #pragma warning restore CS1591
        [EnumMember(Value = "EVENTS")]
        #pragma warning disable CS1591
        EVENTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "HIGHER_EDUCATION")]
        #pragma warning disable CS1591
        HIGHER_EDUCATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "K12")]
        #pragma warning disable CS1591
        K12,
        #pragma warning restore CS1591
        [EnumMember(Value = "MARKETING")]
        #pragma warning disable CS1591
        MARKETING,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLLING_AND_VOTING_NON_POLITICAL")]
        #pragma warning disable CS1591
        POLLING_AND_VOTING_NON_POLITICAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_ELECTION_CAMPAIGNS")]
        #pragma warning disable CS1591
        POLITICAL_ELECTION_CAMPAIGNS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUBLIC_SERVICE_ANNOUNCEMENT")]
        #pragma warning disable CS1591
        PUBLIC_SERVICE_ANNOUNCEMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECURITY_ALERT")]
        #pragma warning disable CS1591
        SECURITY_ALERT,
        #pragma warning restore CS1591
    }
}
