// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>The source data type, which determines the source of the data and the required configuration parameters.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatasetWarehouseType
    {
        [EnumMember(Value = "DATASET_WAREHOUSE")]
        #pragma warning disable CS1591
        DatasetWarehouse,
        #pragma warning restore CS1591
    }
}
