// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>
    /// Reference to the upstream entity that sources this field. Shape isselected by the `sourceType` discriminator and owned by that upstream, notby this API — adding a new upstream means adding a variant here, notchanging the request shape.Every variant carries `sourceType` via `EntityMetadataBase`, so a clientthat does not recognise a newly added variant can still deserialize thecommon fields rather than failing outright.The owner check for idempotent upserts is scoped to `sourceType` plus thatvariant&apos;s own identity field (`operatorId` for `INTELLIGENCE_OPERATOR`); amismatch against an existing registration&apos;s owner returns `409`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntityMetadata : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Annotation fieldPath key; generic identifier that determines theoutput-schema field. Resolved against the operator identified by`operatorId`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Field { get; set; }
#nullable restore
#else
        public string Field { get; set; }
#endif
        /// <summary>The Intelligence operator ID. Part of the owner check foridempotent upserts — a mismatch against the existingregistration&apos;s `(sourceType, operatorId)` returns `409`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperatorId { get; set; }
#nullable restore
#else
        public string OperatorId { get; set; }
#endif
        /// <summary>Optional, display-only name of the operator as supplied atregistration time. Not part of any uniqueness or validation logic.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperatorName { get; set; }
#nullable restore
#else
        public string OperatorName { get; set; }
#endif
        /// <summary>The kind of upstream entity that sources this field. The value names theentity type itself, so the identifier carried in `entityMetadata` isunambiguous without a lookup (`INTELLIGENCE_OPERATOR` carries an`operatorId`).Adding a new upstream means adding a value here plus its own`entityMetadata` variant — the request shape is unchanged.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.SourceType? SourceType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.EntityMetadata"/> and sets the default values.
        /// </summary>
        public EntityMetadata()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.EntityMetadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.EntityMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.EntityMetadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "field", n => { Field = n.GetStringValue(); } },
                { "operatorId", n => { OperatorId = n.GetStringValue(); } },
                { "operatorName", n => { OperatorName = n.GetStringValue(); } },
                { "sourceType", n => { SourceType = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.SourceType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("field", Field);
            writer.WriteStringValue("operatorId", OperatorId);
            writer.WriteStringValue("operatorName", OperatorName);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.SourceType>("sourceType", SourceType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
