// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Event_enum_level
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEBUG")]
        #pragma warning disable CS1591
        DEBUG,
        #pragma warning restore CS1591
        [EnumMember(Value = "INFO")]
        #pragma warning disable CS1591
        INFO,
        #pragma warning restore CS1591
        [EnumMember(Value = "WARNING")]
        #pragma warning disable CS1591
        WARNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
    }
}
