// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>File based knowledge sources</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FileSourceDetails_type
    {
        [EnumMember(Value = "File")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
    }
}
