// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>HTTP method provided for status callback URL.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Insights_v1_video_room_summary_status_callback_method
    {
        [EnumMember(Value = "GET")]
        #pragma warning disable CS1591
        GET,
        #pragma warning restore CS1591
        [EnumMember(Value = "POST")]
        #pragma warning disable CS1591
        POST,
        #pragma warning restore CS1591
    }
}
