// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Twilio.OpenApiClient.Models.BaseRelayData"/>, <see cref="global::Soenneker.Twilio.OpenApiClient.Models.CallWrapUpRelayData"/>, <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ConfigurationsRelayData"/>, <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ErrorRelayData"/>, <see cref="global::Soenneker.Twilio.OpenApiClient.Models.InterruptRelayData"/>, <see cref="global::Soenneker.Twilio.OpenApiClient.Models.LanguageChangedRelayData"/>, <see cref="global::Soenneker.Twilio.OpenApiClient.Models.LastTokenReceivedRelayData"/>, <see cref="global::Soenneker.Twilio.OpenApiClient.Models.SttLatencyRelayData"/>, <see cref="global::Soenneker.Twilio.OpenApiClient.Models.TtsLatencyRelayData"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InsightsV1CallEventConversationRelayData : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Twilio.OpenApiClient.Models.BaseRelayData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.BaseRelayData? BaseRelayData { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.BaseRelayData BaseRelayData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Twilio.OpenApiClient.Models.CallWrapUpRelayData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.CallWrapUpRelayData? CallWrapUpRelayData { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.CallWrapUpRelayData CallWrapUpRelayData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ConfigurationsRelayData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.ConfigurationsRelayData? ConfigurationsRelayData { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.ConfigurationsRelayData ConfigurationsRelayData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ErrorRelayData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.ErrorRelayData? ErrorRelayData { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.ErrorRelayData ErrorRelayData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Twilio.OpenApiClient.Models.InterruptRelayData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.InterruptRelayData? InterruptRelayData { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.InterruptRelayData InterruptRelayData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Twilio.OpenApiClient.Models.LanguageChangedRelayData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.LanguageChangedRelayData? LanguageChangedRelayData { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.LanguageChangedRelayData LanguageChangedRelayData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Twilio.OpenApiClient.Models.LastTokenReceivedRelayData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.LastTokenReceivedRelayData? LastTokenReceivedRelayData { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.LastTokenReceivedRelayData LastTokenReceivedRelayData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Twilio.OpenApiClient.Models.SttLatencyRelayData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.SttLatencyRelayData? SttLatencyRelayData { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.SttLatencyRelayData SttLatencyRelayData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Twilio.OpenApiClient.Models.TtsLatencyRelayData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.TtsLatencyRelayData? TtsLatencyRelayData { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.TtsLatencyRelayData TtsLatencyRelayData { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.InsightsV1CallEventConversationRelayData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.InsightsV1CallEventConversationRelayData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Twilio.OpenApiClient.Models.InsightsV1CallEventConversationRelayData();
            if("BaseRelayData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BaseRelayData = new global::Soenneker.Twilio.OpenApiClient.Models.BaseRelayData();
            }
            else if("CallWrapUpRelayData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CallWrapUpRelayData = new global::Soenneker.Twilio.OpenApiClient.Models.CallWrapUpRelayData();
            }
            else if("ConfigurationsRelayData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ConfigurationsRelayData = new global::Soenneker.Twilio.OpenApiClient.Models.ConfigurationsRelayData();
            }
            else if("ErrorRelayData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ErrorRelayData = new global::Soenneker.Twilio.OpenApiClient.Models.ErrorRelayData();
            }
            else if("InterruptRelayData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InterruptRelayData = new global::Soenneker.Twilio.OpenApiClient.Models.InterruptRelayData();
            }
            else if("LanguageChangedRelayData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LanguageChangedRelayData = new global::Soenneker.Twilio.OpenApiClient.Models.LanguageChangedRelayData();
            }
            else if("LastTokenReceivedRelayData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LastTokenReceivedRelayData = new global::Soenneker.Twilio.OpenApiClient.Models.LastTokenReceivedRelayData();
            }
            else if("SttLatencyRelayData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SttLatencyRelayData = new global::Soenneker.Twilio.OpenApiClient.Models.SttLatencyRelayData();
            }
            else if("TtsLatencyRelayData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TtsLatencyRelayData = new global::Soenneker.Twilio.OpenApiClient.Models.TtsLatencyRelayData();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BaseRelayData != null)
            {
                return BaseRelayData.GetFieldDeserializers();
            }
            else if(CallWrapUpRelayData != null)
            {
                return CallWrapUpRelayData.GetFieldDeserializers();
            }
            else if(ConfigurationsRelayData != null)
            {
                return ConfigurationsRelayData.GetFieldDeserializers();
            }
            else if(ErrorRelayData != null)
            {
                return ErrorRelayData.GetFieldDeserializers();
            }
            else if(InterruptRelayData != null)
            {
                return InterruptRelayData.GetFieldDeserializers();
            }
            else if(LanguageChangedRelayData != null)
            {
                return LanguageChangedRelayData.GetFieldDeserializers();
            }
            else if(LastTokenReceivedRelayData != null)
            {
                return LastTokenReceivedRelayData.GetFieldDeserializers();
            }
            else if(SttLatencyRelayData != null)
            {
                return SttLatencyRelayData.GetFieldDeserializers();
            }
            else if(TtsLatencyRelayData != null)
            {
                return TtsLatencyRelayData.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(BaseRelayData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.BaseRelayData>(null, BaseRelayData);
            }
            else if(CallWrapUpRelayData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.CallWrapUpRelayData>(null, CallWrapUpRelayData);
            }
            else if(ConfigurationsRelayData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ConfigurationsRelayData>(null, ConfigurationsRelayData);
            }
            else if(ErrorRelayData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ErrorRelayData>(null, ErrorRelayData);
            }
            else if(InterruptRelayData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.InterruptRelayData>(null, InterruptRelayData);
            }
            else if(LanguageChangedRelayData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.LanguageChangedRelayData>(null, LanguageChangedRelayData);
            }
            else if(LastTokenReceivedRelayData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.LastTokenReceivedRelayData>(null, LastTokenReceivedRelayData);
            }
            else if(SttLatencyRelayData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.SttLatencyRelayData>(null, SttLatencyRelayData);
            }
            else if(TtsLatencyRelayData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TtsLatencyRelayData>(null, TtsLatencyRelayData);
            }
        }
    }
}
#pragma warning restore CS0618
