// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Intelligence_v2_service : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The unique SID identifier of the Account the Service belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSid { get; set; }
#nullable restore
#else
        public string AccountSid { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Instructs the Speech Recognition service to automatically redact PII from all transcripts made on this service.</summary>
        public bool? AutoRedaction { get; set; }
        /// <summary>Instructs the Speech Recognition service to automatically transcribe all recordings made on the account.</summary>
        public bool? AutoTranscribe { get; set; }
        /// <summary>&quot;Data logging allows Twilio to improve the quality of the speech recognition &amp; language understanding services through using customer data to refine, fine tune and evaluate machine learning models.Note: Data logging cannot be activated via API, only via www.twilio.com, as it requires additional consent.&quot;</summary>
        public bool? DataLogging { get; set; }
        /// <summary>The date that this Service was created, given in ISO 8601 format.</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date that this Service was updated, given in ISO 8601 format.</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The unique SID identifier of the Public Key resource used to encrypt the sentences and operator results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EncryptionCredentialSid { get; set; }
#nullable restore
#else
        public string EncryptionCredentialSid { get; set; }
#endif
        /// <summary>A human readable description of this resource, up to 64 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>The language code set during Service creation determines the Transcription language for all call recordings processed by that Service. The default is en-US if no language code is set. A Service can only support one language code, and it cannot be updated once it&apos;s set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LanguageCode { get; set; }
#nullable restore
#else
        public string LanguageCode { get; set; }
#endif
        /// <summary>Instructs the Speech Recognition service to automatically redact PII from all transcripts media made on this service. The auto_redaction flag must be enabled, results in error otherwise.</summary>
        public bool? MediaRedaction { get; set; }
        /// <summary>Operator sids attached to this service, read only</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ReadOnlyAttachedOperatorSids { get; set; }
#nullable restore
#else
        public List<string> ReadOnlyAttachedOperatorSids { get; set; }
#endif
        /// <summary>A 34 character string that uniquely identifies this Service.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sid { get; set; }
#nullable restore
#else
        public string Sid { get; set; }
#endif
        /// <summary>Provides a unique and addressable name to be assigned to this Service, assigned by the developer, to be optionally used in addition to SID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UniqueName { get; set; }
#nullable restore
#else
        public string UniqueName { get; set; }
#endif
        /// <summary>The URL of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The version number of this Service.</summary>
        public int? Version { get; set; }
        /// <summary>The HTTP method for the Webhook. One of `GET` or `POST`.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Service_enum_http_method? WebhookHttpMethod { get; set; }
        /// <summary>The URL Twilio will request when executing the Webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookUrl { get; set; }
#nullable restore
#else
        public string WebhookUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Intelligence_v2_service"/> and sets the default values.
        /// </summary>
        public Intelligence_v2_service()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Intelligence_v2_service"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Intelligence_v2_service CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Intelligence_v2_service();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_sid", n => { AccountSid = n.GetStringValue(); } },
                { "auto_redaction", n => { AutoRedaction = n.GetBoolValue(); } },
                { "auto_transcribe", n => { AutoTranscribe = n.GetBoolValue(); } },
                { "data_logging", n => { DataLogging = n.GetBoolValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "encryption_credential_sid", n => { EncryptionCredentialSid = n.GetStringValue(); } },
                { "friendly_name", n => { FriendlyName = n.GetStringValue(); } },
                { "language_code", n => { LanguageCode = n.GetStringValue(); } },
                { "media_redaction", n => { MediaRedaction = n.GetBoolValue(); } },
                { "read_only_attached_operator_sids", n => { ReadOnlyAttachedOperatorSids = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sid", n => { Sid = n.GetStringValue(); } },
                { "unique_name", n => { UniqueName = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
                { "webhook_http_method", n => { WebhookHttpMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Service_enum_http_method>(); } },
                { "webhook_url", n => { WebhookUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_sid", AccountSid);
            writer.WriteBoolValue("auto_redaction", AutoRedaction);
            writer.WriteBoolValue("auto_transcribe", AutoTranscribe);
            writer.WriteBoolValue("data_logging", DataLogging);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteStringValue("encryption_credential_sid", EncryptionCredentialSid);
            writer.WriteStringValue("friendly_name", FriendlyName);
            writer.WriteStringValue("language_code", LanguageCode);
            writer.WriteBoolValue("media_redaction", MediaRedaction);
            writer.WriteCollectionOfPrimitiveValues<string>("read_only_attached_operator_sids", ReadOnlyAttachedOperatorSids);
            writer.WriteStringValue("sid", Sid);
            writer.WriteStringValue("unique_name", UniqueName);
            writer.WriteStringValue("url", Url);
            writer.WriteIntValue("version", Version);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Service_enum_http_method>("webhook_http_method", WebhookHttpMethod);
            writer.WriteStringValue("webhook_url", WebhookUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
