// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>&quot;The type of the Transfer. Can be: `cold`, `warm`.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Interaction_transfer_enum_transfer_type
    {
        [EnumMember(Value = "warm")]
        #pragma warning disable CS1591
        Warm,
        #pragma warning restore CS1591
        [EnumMember(Value = "cold")]
        #pragma warning disable CS1591
        Cold,
        #pragma warning restore CS1591
        [EnumMember(Value = "external")]
        #pragma warning disable CS1591
        External,
        #pragma warning restore CS1591
    }
}
