// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Ip_messaging_v2_service_binding : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account_sid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSid { get; set; }
#nullable restore
#else
        public string AccountSid { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The binding_type property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_ip_messaging_v2_binding_enum_binding_type? BindingType { get; set; }
        /// <summary>The credential_sid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CredentialSid { get; set; }
#nullable restore
#else
        public string CredentialSid { get; set; }
#endif
        /// <summary>The date_created property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date_updated property</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The endpoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>The identity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Identity { get; set; }
#nullable restore
#else
        public string Identity { get; set; }
#endif
        /// <summary>The links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.Ip_messaging_v2_service_binding_links? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.Ip_messaging_v2_service_binding_links Links { get; set; }
#endif
        /// <summary>The message_types property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MessageTypes { get; set; }
#nullable restore
#else
        public List<string> MessageTypes { get; set; }
#endif
        /// <summary>The service_sid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceSid { get; set; }
#nullable restore
#else
        public string ServiceSid { get; set; }
#endif
        /// <summary>The sid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sid { get; set; }
#nullable restore
#else
        public string Sid { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Ip_messaging_v2_service_binding"/> and sets the default values.
        /// </summary>
        public Ip_messaging_v2_service_binding()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Ip_messaging_v2_service_binding"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Ip_messaging_v2_service_binding CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Ip_messaging_v2_service_binding();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_sid", n => { AccountSid = n.GetStringValue(); } },
                { "binding_type", n => { BindingType = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_ip_messaging_v2_binding_enum_binding_type>(); } },
                { "credential_sid", n => { CredentialSid = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "identity", n => { Identity = n.GetStringValue(); } },
                { "links", n => { Links = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Ip_messaging_v2_service_binding_links>(global::Soenneker.Twilio.OpenApiClient.Models.Ip_messaging_v2_service_binding_links.CreateFromDiscriminatorValue); } },
                { "message_types", n => { MessageTypes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "service_sid", n => { ServiceSid = n.GetStringValue(); } },
                { "sid", n => { Sid = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_sid", AccountSid);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_ip_messaging_v2_binding_enum_binding_type>("binding_type", BindingType);
            writer.WriteStringValue("credential_sid", CredentialSid);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteStringValue("identity", Identity);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Ip_messaging_v2_service_binding_links>("links", Links);
            writer.WriteCollectionOfPrimitiveValues<string>("message_types", MessageTypes);
            writer.WriteStringValue("service_sid", ServiceSid);
            writer.WriteStringValue("sid", Sid);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
