// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Numbers_v1_porting_losing_carrier_information : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account number of the customer for the losing carrier. Only require for mobile phone numbers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>The account phone number of the customer for the losing carrier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountTelephoneNumber { get; set; }
#nullable restore
#else
        public string AccountTelephoneNumber { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_address? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_address Address { get; set; }
#endif
        /// <summary>If you already have an Address SID that represents the address needed for the LOA, you can provide an Address SID instead of providing the address object in the request body. This will copy the address into the port in request. If changes are made to the Address SID after port in request creation, those changes will not be reflected in the port in request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressSid { get; set; }
#nullable restore
#else
        public string AddressSid { get; set; }
#endif
        /// <summary>The first and last name of the person listed with the losing carrier who is authorized to make changes on the account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizedRepresentative { get; set; }
#nullable restore
#else
        public string AuthorizedRepresentative { get; set; }
#endif
        /// <summary>Email address of the person (owner of the number) who will sign the letter of authorization for the port in request. This email address should belong to the person named in as the authorized representative.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizedRepresentativeEmail { get; set; }
#nullable restore
#else
        public string AuthorizedRepresentativeEmail { get; set; }
#endif
        /// <summary>The authorized_representative_katakana property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizedRepresentativeKatakana { get; set; }
#nullable restore
#else
        public string AuthorizedRepresentativeKatakana { get; set; }
#endif
        /// <summary>The building property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Building { get; set; }
#nullable restore
#else
        public string Building { get; set; }
#endif
        /// <summary>Customer name as it is registered with the losing carrier. This can be an individual or a business name depending on the customer type selected.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerName { get; set; }
#nullable restore
#else
        public string CustomerName { get; set; }
#endif
        /// <summary>&quot;The type of customer account in the losing carrier. This should either be: &apos;Individual&apos; or &apos;Business&apos;.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_losing_carrier_information_customer_type? CustomerType { get; set; }
        /// <summary>The katakana_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KatakanaName { get; set; }
#nullable restore
#else
        public string KatakanaName { get; set; }
#endif
        /// <summary>The sub_municipality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubMunicipality { get; set; }
#nullable restore
#else
        public string SubMunicipality { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_losing_carrier_information"/> and sets the default values.
        /// </summary>
        public Numbers_v1_porting_losing_carrier_information()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_losing_carrier_information"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_losing_carrier_information CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_losing_carrier_information();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_number", n => { AccountNumber = n.GetStringValue(); } },
                { "account_telephone_number", n => { AccountTelephoneNumber = n.GetStringValue(); } },
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_address>(global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_address.CreateFromDiscriminatorValue); } },
                { "address_sid", n => { AddressSid = n.GetStringValue(); } },
                { "authorized_representative", n => { AuthorizedRepresentative = n.GetStringValue(); } },
                { "authorized_representative_email", n => { AuthorizedRepresentativeEmail = n.GetStringValue(); } },
                { "authorized_representative_katakana", n => { AuthorizedRepresentativeKatakana = n.GetStringValue(); } },
                { "building", n => { Building = n.GetStringValue(); } },
                { "customer_name", n => { CustomerName = n.GetStringValue(); } },
                { "customer_type", n => { CustomerType = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_losing_carrier_information_customer_type>(); } },
                { "katakana_name", n => { KatakanaName = n.GetStringValue(); } },
                { "sub_municipality", n => { SubMunicipality = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_number", AccountNumber);
            writer.WriteStringValue("account_telephone_number", AccountTelephoneNumber);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_address>("address", Address);
            writer.WriteStringValue("address_sid", AddressSid);
            writer.WriteStringValue("authorized_representative", AuthorizedRepresentative);
            writer.WriteStringValue("authorized_representative_email", AuthorizedRepresentativeEmail);
            writer.WriteStringValue("authorized_representative_katakana", AuthorizedRepresentativeKatakana);
            writer.WriteStringValue("building", Building);
            writer.WriteStringValue("customer_name", CustomerName);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Numbers_v1_porting_losing_carrier_information_customer_type>("customer_type", CustomerType);
            writer.WriteStringValue("katakana_name", KatakanaName);
            writer.WriteStringValue("sub_municipality", SubMunicipality);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
