// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>Operators with this Operator Type are executed using this provider. Possible values: twilio, amazon, openai.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OperatorTypeEnumProvider
    {
        [EnumMember(Value = "twilio")]
        #pragma warning disable CS1591
        Twilio,
        #pragma warning restore CS1591
        [EnumMember(Value = "amazon")]
        #pragma warning disable CS1591
        Amazon,
        #pragma warning restore CS1591
        [EnumMember(Value = "openai")]
        #pragma warning disable CS1591
        Openai,
        #pragma warning restore CS1591
    }
}
