// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>A scimType error code as defined in RFC7644</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ScimError_scimType
    {
        [EnumMember(Value = "invalidFilter")]
        #pragma warning disable CS1591
        InvalidFilter,
        #pragma warning restore CS1591
        [EnumMember(Value = "uniqueness")]
        #pragma warning disable CS1591
        Uniqueness,
        #pragma warning restore CS1591
        [EnumMember(Value = "mutability")]
        #pragma warning disable CS1591
        Mutability,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalidValue")]
        #pragma warning disable CS1591
        InvalidValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalidSyntax")]
        #pragma warning disable CS1591
        InvalidSyntax,
        #pragma warning restore CS1591
    }
}
