// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ShortCodeApplicationSmsCampaignDetailsCustomerCareChannel
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TOLL_FREE_NUMBER")]
        #pragma warning disable CS1591
        TollFreeNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
    }
}
