// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>
    /// Compliance keywords for the application.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShortCodeApplication_compliance_keywords : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aide property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Aide { get; set; }
#nullable restore
#else
        public string Aide { get; set; }
#endif
        /// <summary>The arret property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Arret { get; set; }
#nullable restore
#else
        public string Arret { get; set; }
#endif
        /// <summary>The help property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Help { get; set; }
#nullable restore
#else
        public string Help { get; set; }
#endif
        /// <summary>The info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Info { get; set; }
#nullable restore
#else
        public string Info { get; set; }
#endif
        /// <summary>The opt_out_filtering property</summary>
        public bool? OptOutFiltering { get; set; }
        /// <summary>The stop property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Stop { get; set; }
#nullable restore
#else
        public string Stop { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_compliance_keywords"/> and sets the default values.
        /// </summary>
        public ShortCodeApplication_compliance_keywords()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_compliance_keywords"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_compliance_keywords CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_compliance_keywords();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aide", n => { Aide = n.GetStringValue(); } },
                { "arret", n => { Arret = n.GetStringValue(); } },
                { "help", n => { Help = n.GetStringValue(); } },
                { "info", n => { Info = n.GetStringValue(); } },
                { "opt_out_filtering", n => { OptOutFiltering = n.GetBoolValue(); } },
                { "stop", n => { Stop = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("aide", Aide);
            writer.WriteStringValue("arret", Arret);
            writer.WriteStringValue("help", Help);
            writer.WriteStringValue("info", Info);
            writer.WriteBoolValue("opt_out_filtering", OptOutFiltering);
            writer.WriteStringValue("stop", Stop);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
