// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ShortCodeApplication : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Account SID associated with the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSid { get; set; }
#nullable restore
#else
        public string AccountSid { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Application Requirements SID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationRequirementsSid { get; set; }
#nullable restore
#else
        public string ApplicationRequirementsSid { get; set; }
#endif
        /// <summary>The version of the application requirements.</summary>
        public int? ApplicationRequirementsVersion { get; set; }
        /// <summary>The Bundle SID for regulatory compliance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BundleSid { get; set; }
#nullable restore
#else
        public string BundleSid { get; set; }
#endif
        /// <summary>Business information associated with the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_business_information? BusinessInformation { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_business_information BusinessInformation { get; set; }
#endif
        /// <summary>Compliance keywords for the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_compliance_keywords? ComplianceKeywords { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_compliance_keywords ComplianceKeywords { get; set; }
#endif
        /// <summary>Content examples for the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_content_examples? ContentExamples { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_content_examples ContentExamples { get; set; }
#endif
        /// <summary>The identity of the user who created the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The date and time the application was created.</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date and time the application was last updated.</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The friendly name of the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>The ISO country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IsoCountry { get; set; }
#nullable restore
#else
        public string IsoCountry { get; set; }
#endif
        /// <summary>The notification emails for the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NotificationEmails { get; set; }
#nullable restore
#else
        public List<string> NotificationEmails { get; set; }
#endif
        /// <summary>The reviewer of the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reviewer { get; set; }
#nullable restore
#else
        public string Reviewer { get; set; }
#endif
        /// <summary>Setup configuration for the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_setup? Setup { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_setup Setup { get; set; }
#endif
        /// <summary>The unique identifier of the Short Code Application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sid { get; set; }
#nullable restore
#else
        public string Sid { get; set; }
#endif
        /// <summary>SMS campaign details for the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_sms_campaign_details? SmsCampaignDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_sms_campaign_details SmsCampaignDetails { get; set; }
#endif
        /// <summary>The state of the application.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_state? State { get; set; }
        /// <summary>The identity of the user who last updated the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>User sign-up configuration for the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_user_sign_up? UserSignUp { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_user_sign_up UserSignUp { get; set; }
#endif
        /// <summary>The Zendesk ticket ID associated with the application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ZendeskTicketId { get; set; }
#nullable restore
#else
        public string ZendeskTicketId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication"/> and sets the default values.
        /// </summary>
        public ShortCodeApplication()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_sid", n => { AccountSid = n.GetStringValue(); } },
                { "application_requirements_sid", n => { ApplicationRequirementsSid = n.GetStringValue(); } },
                { "application_requirements_version", n => { ApplicationRequirementsVersion = n.GetIntValue(); } },
                { "bundle_sid", n => { BundleSid = n.GetStringValue(); } },
                { "business_information", n => { BusinessInformation = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_business_information>(global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_business_information.CreateFromDiscriminatorValue); } },
                { "compliance_keywords", n => { ComplianceKeywords = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_compliance_keywords>(global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_compliance_keywords.CreateFromDiscriminatorValue); } },
                { "content_examples", n => { ContentExamples = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_content_examples>(global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_content_examples.CreateFromDiscriminatorValue); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "friendly_name", n => { FriendlyName = n.GetStringValue(); } },
                { "iso_country", n => { IsoCountry = n.GetStringValue(); } },
                { "notification_emails", n => { NotificationEmails = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "reviewer", n => { Reviewer = n.GetStringValue(); } },
                { "setup", n => { Setup = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_setup>(global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_setup.CreateFromDiscriminatorValue); } },
                { "sid", n => { Sid = n.GetStringValue(); } },
                { "sms_campaign_details", n => { SmsCampaignDetails = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_sms_campaign_details>(global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_sms_campaign_details.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_state>(); } },
                { "updated_by", n => { UpdatedBy = n.GetStringValue(); } },
                { "user_sign_up", n => { UserSignUp = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_user_sign_up>(global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_user_sign_up.CreateFromDiscriminatorValue); } },
                { "zendesk_ticket_id", n => { ZendeskTicketId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_sid", AccountSid);
            writer.WriteStringValue("application_requirements_sid", ApplicationRequirementsSid);
            writer.WriteIntValue("application_requirements_version", ApplicationRequirementsVersion);
            writer.WriteStringValue("bundle_sid", BundleSid);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_business_information>("business_information", BusinessInformation);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_compliance_keywords>("compliance_keywords", ComplianceKeywords);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_content_examples>("content_examples", ContentExamples);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteStringValue("friendly_name", FriendlyName);
            writer.WriteStringValue("iso_country", IsoCountry);
            writer.WriteCollectionOfPrimitiveValues<string>("notification_emails", NotificationEmails);
            writer.WriteStringValue("reviewer", Reviewer);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_setup>("setup", Setup);
            writer.WriteStringValue("sid", Sid);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_sms_campaign_details>("sms_campaign_details", SmsCampaignDetails);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_state>("state", State);
            writer.WriteStringValue("updated_by", UpdatedBy);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ShortCodeApplication_user_sign_up>("user_sign_up", UserSignUp);
            writer.WriteStringValue("zendesk_ticket_id", ZendeskTicketId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
