// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ShortCodeApplicationSmsCampaignDetailsCampaignFrequencyItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ONE_MESSAGE_PER_SIGNUP")]
        #pragma warning disable CS1591
        OneMessagePerSignup,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIMITED_NUMBER_OF_MESSAGES_PER_SIGNUP")]
        #pragma warning disable CS1591
        LimitedNumberOfMessagesPerSignup,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIMITED_NUMBER_OF_MESSAGES_AT_RECURRING_INTERVALS")]
        #pragma warning disable CS1591
        LimitedNumberOfMessagesAtRecurringIntervals,
        #pragma warning restore CS1591
        [EnumMember(Value = "VARIABLE_NUMBER_OF_MESSAGES_AT_UNPREDICTABLE_INTERVALS")]
        #pragma warning disable CS1591
        VariableNumberOfMessagesAtUnpredictableIntervals,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIMITED_NUMBER_OF_MESSAGES_IN_RESPONSE_TO_KEYWORDS")]
        #pragma warning disable CS1591
        LimitedNumberOfMessagesInResponseToKeywords,
        #pragma warning restore CS1591
    }
}
