// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Studio_v2_flow : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Flow resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSid { get; set; }
#nullable restore
#else
        public string AccountSid { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The SID of the User that created or last updated the Flow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorSid { get; set; }
#nullable restore
#else
        public string AuthorSid { get; set; }
#endif
        /// <summary>Description of change made in the revision.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommitMessage { get; set; }
#nullable restore
#else
        public string CommitMessage { get; set; }
#endif
        /// <summary>The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>JSON representation of flow definition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Definition { get; set; }
#nullable restore
#else
        public UntypedNode Definition { get; set; }
#endif
        /// <summary>List of error in the flow definition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_errors>? Errors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_errors> Errors { get; set; }
#endif
        /// <summary>The string that you assigned to describe the Flow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>The URLs of the Flow&apos;s nested resources.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_links? Links { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_links Links { get; set; }
#endif
        /// <summary>The latest revision number of the Flow&apos;s definition.</summary>
        public int? Revision { get; set; }
        /// <summary>The unique string that we created to identify the Flow resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sid { get; set; }
#nullable restore
#else
        public string Sid { get; set; }
#endif
        /// <summary>&quot;The status of the Flow. Can be: `draft` or `published`.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_studio_v2_flow_enum_status? Status { get; set; }
        /// <summary>The absolute URL of the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>Boolean if the flow definition is valid.</summary>
        public bool? Valid { get; set; }
        /// <summary>List of warnings in the flow definition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_warnings>? Warnings { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_warnings> Warnings { get; set; }
#endif
        /// <summary>The webhook_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookUrl { get; set; }
#nullable restore
#else
        public string WebhookUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow"/> and sets the default values.
        /// </summary>
        public Studio_v2_flow()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_sid", n => { AccountSid = n.GetStringValue(); } },
                { "author_sid", n => { AuthorSid = n.GetStringValue(); } },
                { "commit_message", n => { CommitMessage = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "definition", n => { Definition = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_errors>(global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_errors.CreateFromDiscriminatorValue)?.AsList(); } },
                { "friendly_name", n => { FriendlyName = n.GetStringValue(); } },
                { "links", n => { Links = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_links>(global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_links.CreateFromDiscriminatorValue); } },
                { "revision", n => { Revision = n.GetIntValue(); } },
                { "sid", n => { Sid = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_studio_v2_flow_enum_status>(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "valid", n => { Valid = n.GetBoolValue(); } },
                { "warnings", n => { Warnings = n.GetCollectionOfObjectValues<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_warnings>(global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_warnings.CreateFromDiscriminatorValue)?.AsList(); } },
                { "webhook_url", n => { WebhookUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_sid", AccountSid);
            writer.WriteStringValue("author_sid", AuthorSid);
            writer.WriteStringValue("commit_message", CommitMessage);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteObjectValue<UntypedNode>("definition", Definition);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_errors>("errors", Errors);
            writer.WriteStringValue("friendly_name", FriendlyName);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_links>("links", Links);
            writer.WriteIntValue("revision", Revision);
            writer.WriteStringValue("sid", Sid);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_studio_v2_flow_enum_status>("status", Status);
            writer.WriteStringValue("url", Url);
            writer.WriteBoolValue("valid", Valid);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Twilio.OpenApiClient.Models.Studio_v2_flow_warnings>("warnings", Warnings);
            writer.WriteStringValue("webhook_url", WebhookUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
