// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Twilio_supersim_v1_CreateFleet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Defines whether SIMs in the Fleet are capable of using 2G/3G/4G/LTE/CAT-M data connectivity. Defaults to `true`.</summary>
        public bool? DataEnabled { get; set; }
        /// <summary>The total data usage (download and upload combined) in Megabytes that each Super SIM assigned to the Fleet can consume during a billing period (normally one month). Value must be between 1MB (1) and 2TB (2,000,000). Defaults to 1GB (1,000).</summary>
        public int? DataLimit { get; set; }
        /// <summary>A string representing the HTTP method to use when making a request to `ip_commands_url`. Can be one of `POST` or `GET`. Defaults to `POST`.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet_IpCommandsMethod? IpCommandsMethod { get; set; }
        /// <summary>The URL that will receive a webhook when a Super SIM in the Fleet is used to send an IP Command from your device to a special IP address. Your server should respond with an HTTP status code in the 200 range; any response body will be ignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IpCommandsUrl { get; set; }
#nullable restore
#else
        public string IpCommandsUrl { get; set; }
#endif
        /// <summary>The SID or unique name of the Network Access Profile that will control which cellular networks the Fleet&apos;s SIMs can connect to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NetworkAccessProfile { get; set; }
#nullable restore
#else
        public string NetworkAccessProfile { get; set; }
#endif
        /// <summary>Defines whether SIMs in the Fleet are capable of sending and receiving machine-to-machine SMS via Commands. Defaults to `true`.</summary>
        public bool? SmsCommandsEnabled { get; set; }
        /// <summary>A string representing the HTTP method to use when making a request to `sms_commands_url`. Can be one of `POST` or `GET`. Defaults to `POST`.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet_SmsCommandsMethod? SmsCommandsMethod { get; set; }
        /// <summary>The URL that will receive a webhook when a Super SIM in the Fleet is used to send an SMS from your device to the SMS Commands number. Your server should respond with an HTTP status code in the 200 range; any response body will be ignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmsCommandsUrl { get; set; }
#nullable restore
#else
        public string SmsCommandsUrl { get; set; }
#endif
        /// <summary>An application-defined string that uniquely identifies the resource. It can be used in place of the resource&apos;s `sid` in the URL to address the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UniqueName { get; set; }
#nullable restore
#else
        public string UniqueName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet"/> and sets the default values.
        /// </summary>
        public Twilio_supersim_v1_CreateFleet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "DataEnabled", n => { DataEnabled = n.GetBoolValue(); } },
                { "DataLimit", n => { DataLimit = n.GetIntValue(); } },
                { "IpCommandsMethod", n => { IpCommandsMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet_IpCommandsMethod>(); } },
                { "IpCommandsUrl", n => { IpCommandsUrl = n.GetStringValue(); } },
                { "NetworkAccessProfile", n => { NetworkAccessProfile = n.GetStringValue(); } },
                { "SmsCommandsEnabled", n => { SmsCommandsEnabled = n.GetBoolValue(); } },
                { "SmsCommandsMethod", n => { SmsCommandsMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet_SmsCommandsMethod>(); } },
                { "SmsCommandsUrl", n => { SmsCommandsUrl = n.GetStringValue(); } },
                { "UniqueName", n => { UniqueName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("DataEnabled", DataEnabled);
            writer.WriteIntValue("DataLimit", DataLimit);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet_IpCommandsMethod>("IpCommandsMethod", IpCommandsMethod);
            writer.WriteStringValue("IpCommandsUrl", IpCommandsUrl);
            writer.WriteStringValue("NetworkAccessProfile", NetworkAccessProfile);
            writer.WriteBoolValue("SmsCommandsEnabled", SmsCommandsEnabled);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_supersim_v1_CreateFleet_SmsCommandsMethod>("SmsCommandsMethod", SmsCommandsMethod);
            writer.WriteStringValue("SmsCommandsUrl", SmsCommandsUrl);
            writer.WriteStringValue("UniqueName", UniqueName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
