// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Twilio_api_v2010_CreateRealtimeTranscription : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the Conversations Configuration for customizing conversation behavior in Intelligence Service</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationConfiguration { get; set; }
#nullable restore
#else
        public string ConversationConfiguration { get; set; }
#endif
        /// <summary>The ID of the Conversation for associating this Transcription with an existing Conversation in Intelligence Service</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId { get; set; }
#nullable restore
#else
        public string ConversationId { get; set; }
#endif
        /// <summary>The provider will add punctuation to recognition result</summary>
        public bool? EnableAutomaticPunctuation { get; set; }
        /// <summary>Whether the callback includes raw provider data.</summary>
        public bool? EnableProviderData { get; set; }
        /// <summary>A Phrase contains words and phrase &quot;hints&quot; so that the speech recognition engine is more likely to recognize them.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hints { get; set; }
#nullable restore
#else
        public string Hints { get; set; }
#endif
        /// <summary>Friendly name given to the Inbound Track</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InboundTrackLabel { get; set; }
#nullable restore
#else
        public string InboundTrackLabel { get; set; }
#endif
        /// <summary>The SID or unique name of the [Intelligence Service](https://www.twilio.com/docs/conversational-intelligence/api/service-resource) for persisting transcripts and running post-call Language Operators</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntelligenceService { get; set; }
#nullable restore
#else
        public string IntelligenceService { get; set; }
#endif
        /// <summary>Language code used by the transcription engine, specified in [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LanguageCode { get; set; }
#nullable restore
#else
        public string LanguageCode { get; set; }
#endif
        /// <summary>The user-specified name of this Transcription, if one was given when the Transcription was created. This may be used to stop the Transcription.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Friendly name given to the Outbound Track</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutboundTrackLabel { get; set; }
#nullable restore
#else
        public string OutboundTrackLabel { get; set; }
#endif
        /// <summary>Indicates if partial results are going to be sent to the customer</summary>
        public bool? PartialResults { get; set; }
        /// <summary>indicates if the server will attempt to filter out profanities, replacing all but the initial character in each filtered word with asterisks</summary>
        public bool? ProfanityFilter { get; set; }
        /// <summary>Recognition model used by the transcription engine, among those supported by the provider</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpeechModel { get; set; }
#nullable restore
#else
        public string SpeechModel { get; set; }
#endif
        /// <summary>The http method for the status_callback (one of GET, POST).</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateRealtimeTranscription_StatusCallbackMethod? StatusCallbackMethod { get; set; }
        /// <summary>Absolute URL of the status callback.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusCallbackUrl { get; set; }
#nullable restore
#else
        public string StatusCallbackUrl { get; set; }
#endif
        /// <summary>One of `inbound_track`, `outbound_track`, `both_tracks`.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Realtime_transcription_enum_track? Track { get; set; }
        /// <summary>Definition of the transcription engine to be used, among those supported by Twilio</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TranscriptionEngine { get; set; }
#nullable restore
#else
        public string TranscriptionEngine { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateRealtimeTranscription"/> and sets the default values.
        /// </summary>
        public Twilio_api_v2010_CreateRealtimeTranscription()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateRealtimeTranscription"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateRealtimeTranscription CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateRealtimeTranscription();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ConversationConfiguration", n => { ConversationConfiguration = n.GetStringValue(); } },
                { "ConversationId", n => { ConversationId = n.GetStringValue(); } },
                { "EnableAutomaticPunctuation", n => { EnableAutomaticPunctuation = n.GetBoolValue(); } },
                { "EnableProviderData", n => { EnableProviderData = n.GetBoolValue(); } },
                { "Hints", n => { Hints = n.GetStringValue(); } },
                { "InboundTrackLabel", n => { InboundTrackLabel = n.GetStringValue(); } },
                { "IntelligenceService", n => { IntelligenceService = n.GetStringValue(); } },
                { "LanguageCode", n => { LanguageCode = n.GetStringValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "OutboundTrackLabel", n => { OutboundTrackLabel = n.GetStringValue(); } },
                { "PartialResults", n => { PartialResults = n.GetBoolValue(); } },
                { "ProfanityFilter", n => { ProfanityFilter = n.GetBoolValue(); } },
                { "SpeechModel", n => { SpeechModel = n.GetStringValue(); } },
                { "StatusCallbackMethod", n => { StatusCallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateRealtimeTranscription_StatusCallbackMethod>(); } },
                { "StatusCallbackUrl", n => { StatusCallbackUrl = n.GetStringValue(); } },
                { "Track", n => { Track = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Realtime_transcription_enum_track>(); } },
                { "TranscriptionEngine", n => { TranscriptionEngine = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ConversationConfiguration", ConversationConfiguration);
            writer.WriteStringValue("ConversationId", ConversationId);
            writer.WriteBoolValue("EnableAutomaticPunctuation", EnableAutomaticPunctuation);
            writer.WriteBoolValue("EnableProviderData", EnableProviderData);
            writer.WriteStringValue("Hints", Hints);
            writer.WriteStringValue("InboundTrackLabel", InboundTrackLabel);
            writer.WriteStringValue("IntelligenceService", IntelligenceService);
            writer.WriteStringValue("LanguageCode", LanguageCode);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("OutboundTrackLabel", OutboundTrackLabel);
            writer.WriteBoolValue("PartialResults", PartialResults);
            writer.WriteBoolValue("ProfanityFilter", ProfanityFilter);
            writer.WriteStringValue("SpeechModel", SpeechModel);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateRealtimeTranscription_StatusCallbackMethod>("StatusCallbackMethod", StatusCallbackMethod);
            writer.WriteStringValue("StatusCallbackUrl", StatusCallbackUrl);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Realtime_transcription_enum_track>("Track", Track);
            writer.WriteStringValue("TranscriptionEngine", TranscriptionEngine);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
