// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Twilio_notify_v1_CreateService : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Deprecated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlexaSkillId { get; set; }
#nullable restore
#else
        public string AlexaSkillId { get; set; }
#endif
        /// <summary>The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for APN Bindings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApnCredentialSid { get; set; }
#nullable restore
#else
        public string ApnCredentialSid { get; set; }
#endif
        /// <summary>Deprecated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultAlexaNotificationProtocolVersion { get; set; }
#nullable restore
#else
        public string DefaultAlexaNotificationProtocolVersion { get; set; }
#endif
        /// <summary>The protocol version to use for sending APNS notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultApnNotificationProtocolVersion { get; set; }
#nullable restore
#else
        public string DefaultApnNotificationProtocolVersion { get; set; }
#endif
        /// <summary>The protocol version to use for sending FCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultFcmNotificationProtocolVersion { get; set; }
#nullable restore
#else
        public string DefaultFcmNotificationProtocolVersion { get; set; }
#endif
        /// <summary>The protocol version to use for sending GCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultGcmNotificationProtocolVersion { get; set; }
#nullable restore
#else
        public string DefaultGcmNotificationProtocolVersion { get; set; }
#endif
        /// <summary>Callback configuration that enables delivery callbacks, default false</summary>
        public bool? DeliveryCallbackEnabled { get; set; }
        /// <summary>URL to send delivery status callback.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryCallbackUrl { get; set; }
#nullable restore
#else
        public string DeliveryCallbackUrl { get; set; }
#endif
        /// <summary>Deprecated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FacebookMessengerPageId { get; set; }
#nullable restore
#else
        public string FacebookMessengerPageId { get; set; }
#endif
        /// <summary>The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for FCM Bindings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FcmCredentialSid { get; set; }
#nullable restore
#else
        public string FcmCredentialSid { get; set; }
#endif
        /// <summary>A descriptive string that you create to describe the resource. It can be up to 64 characters long.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for GCM Bindings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GcmCredentialSid { get; set; }
#nullable restore
#else
        public string GcmCredentialSid { get; set; }
#endif
        /// <summary>&quot;Whether to log notifications. Can be: `true` or `false` and the default is `true`.&quot;</summary>
        public bool? LogEnabled { get; set; }
        /// <summary>The SID of the [Messaging Service](https://www.twilio.com/docs/sms/quickstart#messaging-services) to use for SMS Bindings. This parameter must be set in order to send SMS notifications.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessagingServiceSid { get; set; }
#nullable restore
#else
        public string MessagingServiceSid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_notify_v1_CreateService"/> and sets the default values.
        /// </summary>
        public Twilio_notify_v1_CreateService()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_notify_v1_CreateService"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Twilio_notify_v1_CreateService CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Twilio_notify_v1_CreateService();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AlexaSkillId", n => { AlexaSkillId = n.GetStringValue(); } },
                { "ApnCredentialSid", n => { ApnCredentialSid = n.GetStringValue(); } },
                { "DefaultAlexaNotificationProtocolVersion", n => { DefaultAlexaNotificationProtocolVersion = n.GetStringValue(); } },
                { "DefaultApnNotificationProtocolVersion", n => { DefaultApnNotificationProtocolVersion = n.GetStringValue(); } },
                { "DefaultFcmNotificationProtocolVersion", n => { DefaultFcmNotificationProtocolVersion = n.GetStringValue(); } },
                { "DefaultGcmNotificationProtocolVersion", n => { DefaultGcmNotificationProtocolVersion = n.GetStringValue(); } },
                { "DeliveryCallbackEnabled", n => { DeliveryCallbackEnabled = n.GetBoolValue(); } },
                { "DeliveryCallbackUrl", n => { DeliveryCallbackUrl = n.GetStringValue(); } },
                { "FacebookMessengerPageId", n => { FacebookMessengerPageId = n.GetStringValue(); } },
                { "FcmCredentialSid", n => { FcmCredentialSid = n.GetStringValue(); } },
                { "FriendlyName", n => { FriendlyName = n.GetStringValue(); } },
                { "GcmCredentialSid", n => { GcmCredentialSid = n.GetStringValue(); } },
                { "LogEnabled", n => { LogEnabled = n.GetBoolValue(); } },
                { "MessagingServiceSid", n => { MessagingServiceSid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AlexaSkillId", AlexaSkillId);
            writer.WriteStringValue("ApnCredentialSid", ApnCredentialSid);
            writer.WriteStringValue("DefaultAlexaNotificationProtocolVersion", DefaultAlexaNotificationProtocolVersion);
            writer.WriteStringValue("DefaultApnNotificationProtocolVersion", DefaultApnNotificationProtocolVersion);
            writer.WriteStringValue("DefaultFcmNotificationProtocolVersion", DefaultFcmNotificationProtocolVersion);
            writer.WriteStringValue("DefaultGcmNotificationProtocolVersion", DefaultGcmNotificationProtocolVersion);
            writer.WriteBoolValue("DeliveryCallbackEnabled", DeliveryCallbackEnabled);
            writer.WriteStringValue("DeliveryCallbackUrl", DeliveryCallbackUrl);
            writer.WriteStringValue("FacebookMessengerPageId", FacebookMessengerPageId);
            writer.WriteStringValue("FcmCredentialSid", FcmCredentialSid);
            writer.WriteStringValue("FriendlyName", FriendlyName);
            writer.WriteStringValue("GcmCredentialSid", GcmCredentialSid);
            writer.WriteBoolValue("LogEnabled", LogEnabled);
            writer.WriteStringValue("MessagingServiceSid", MessagingServiceSid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
