// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Twilio_intelligence_v2_CreateCustomOperator : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Operator configuration, following the schema defined by the Operator Type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_intelligence_v2_CreateCustomOperator_Config? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_intelligence_v2_CreateCustomOperator_Config Config { get; set; }
#endif
        /// <summary>A human readable description of the new Operator, up to 64 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>Operator Type for this Operator. References an existing Operator Type resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperatorType { get; set; }
#nullable restore
#else
        public string OperatorType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_intelligence_v2_CreateCustomOperator"/> and sets the default values.
        /// </summary>
        public Twilio_intelligence_v2_CreateCustomOperator()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_intelligence_v2_CreateCustomOperator"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Twilio_intelligence_v2_CreateCustomOperator CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Twilio_intelligence_v2_CreateCustomOperator();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Config", n => { Config = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_intelligence_v2_CreateCustomOperator_Config>(global::Soenneker.Twilio.OpenApiClient.Models.Twilio_intelligence_v2_CreateCustomOperator_Config.CreateFromDiscriminatorValue); } },
                { "FriendlyName", n => { FriendlyName = n.GetStringValue(); } },
                { "OperatorType", n => { OperatorType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_intelligence_v2_CreateCustomOperator_Config>("Config", Config);
            writer.WriteStringValue("FriendlyName", FriendlyName);
            writer.WriteStringValue("OperatorType", OperatorType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
