// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>
    /// The result of a WebAuthn credential registration via `navigator.credentials.create()`, as specified in [AuthenticatorAttestationResponse](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Twilio_verify_v2_UpdatePasskeysFactor_response : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authenticator data and an attestation statement for a new key pair generated by the authenticator.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttestationObject { get; set; }
#nullable restore
#else
        public string AttestationObject { get; set; }
#endif
        /// <summary>This property contains the JSON-compatible serialization of the data passed from the browser to the authenticator in order to generate this credential.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientDataJSON { get; set; }
#nullable restore
#else
        public string ClientDataJSON { get; set; }
#endif
        /// <summary>An array of strings providing hints as to the methods the client could use to communicate with the relevant authenticator of the public key credential to retrieve.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_verify_v2_UpdatePasskeysFactor_response_transports?>? Transports { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_verify_v2_UpdatePasskeysFactor_response_transports?> Transports { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_verify_v2_UpdatePasskeysFactor_response"/> and sets the default values.
        /// </summary>
        public Twilio_verify_v2_UpdatePasskeysFactor_response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_verify_v2_UpdatePasskeysFactor_response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Twilio_verify_v2_UpdatePasskeysFactor_response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Twilio_verify_v2_UpdatePasskeysFactor_response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attestationObject", n => { AttestationObject = n.GetStringValue(); } },
                { "clientDataJSON", n => { ClientDataJSON = n.GetStringValue(); } },
                { "transports", n => { Transports = n.GetCollectionOfEnumValues<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_verify_v2_UpdatePasskeysFactor_response_transports>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("attestationObject", AttestationObject);
            writer.WriteStringValue("clientDataJSON", ClientDataJSON);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_verify_v2_UpdatePasskeysFactor_response_transports>("transports", Transports);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
