// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>&quot;Current status of the Action.- PENDING: Action accepted, awaiting downstream confirmation- COMPLETED: Downstream backend confirmed the action- FAILED: Downstream backend reported a failure&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TwilioConversationsV2FetchConversationAction200_status
    {
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        COMPLETED,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        FAILED,
        #pragma warning restore CS1591
    }
}
