// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>&quot;The HTTP method we should use to call `commands_callback_url`. Can be: `POST` or `GET`. The default is `POST`.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Twilio_wireless_v1_UpdateSim_CommandsCallbackMethod
    {
        [EnumMember(Value = "GET")]
        #pragma warning disable CS1591
        GET,
        #pragma warning restore CS1591
        [EnumMember(Value = "POST")]
        #pragma warning disable CS1591
        POST,
        #pragma warning restore CS1591
    }
}
