// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Twilio_api_v2010_CreateParticipant : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The URL that we should call using the `amd_status_callback_method` to notify customer application whether the call was answered by human, machine or fax.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AmdStatusCallback { get; set; }
#nullable restore
#else
        public string AmdStatusCallback { get; set; }
#endif
        /// <summary>&quot;The HTTP method we should use when calling the `amd_status_callback` URL. Can be: `GET` or `POST` and the default is `POST`.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_AmdStatusCallbackMethod? AmdStatusCallbackMethod { get; set; }
        /// <summary>&quot;Whether to play a notification beep to the conference when the participant joins. Can be: `true`, `false`, `onEnter`, or `onExit`. The default value is `true`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Beep { get; set; }
#nullable restore
#else
        public string Beep { get; set; }
#endif
        /// <summary>The SID of a BYOC (Bring Your Own Carrier) trunk to route this call with. Note that `byoc` is only meaningful when `to` is a phone number; it will otherwise be ignored. (Beta)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Byoc { get; set; }
#nullable restore
#else
        public string Byoc { get; set; }
#endif
        /// <summary>The name that populates the display name in the From header. Must be between 2 and 255 characters. Only applicable for calls to sip address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallerDisplayName { get; set; }
#nullable restore
#else
        public string CallerDisplayName { get; set; }
#endif
        /// <summary>The phone number, Client identifier, or username portion of SIP address that made this call. Phone numbers are in [E.164](https://www.twilio.com/docs/glossary/what-e164) format (e.g., +16175551212). Client identifiers are formatted `client:name`. If using a phone number, it must be a Twilio number or a Verified [outgoing caller id](https://www.twilio.com/docs/voice/api/outgoing-caller-ids) for your account. If the `to` parameter is a phone number, `callerId` must also be a phone number. If `to` is sip address, this value of `callerId` should be a username portion to be used to populate the From header that is passed to the SIP endpoint.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallerId { get; set; }
#nullable restore
#else
        public string CallerId { get; set; }
#endif
        /// <summary>The Reason for the outgoing call. Use it to specify the purpose of the call that is presented on the called party&apos;s phone. (Branded Calls Beta)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallReason { get; set; }
#nullable restore
#else
        public string CallReason { get; set; }
#endif
        /// <summary>The SID of the participant who is being `coached`. The participant being coached is the only participant who can hear the participant who is `coaching`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallSidToCoach { get; set; }
#nullable restore
#else
        public string CallSidToCoach { get; set; }
#endif
        /// <summary>A token string needed to invoke a forwarded call. A call_token is generated when an incoming call is received on a Twilio number. Pass an incoming call&apos;s call_token value to a forwarded call via the call_token parameter when creating a new call. A forwarded call should bear the same CallerID of the original incoming call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallToken { get; set; }
#nullable restore
#else
        public string CallToken { get; set; }
#endif
        /// <summary>The URL that we should use to deliver `push call notification`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientNotificationUrl { get; set; }
#nullable restore
#else
        public string ClientNotificationUrl { get; set; }
#endif
        /// <summary>&quot;Whether the participant is coaching another call. Can be: `true` or `false`. If not present, defaults to `false` unless `call_sid_to_coach` is defined. If `true`, `call_sid_to_coach` must be defined.&quot;</summary>
        public bool? Coaching { get; set; }
        /// <summary>&quot;Whether to record the conference the participant is joining. Can be: `true`, `false`, `record-from-start`, and `do-not-record`. The default value is `false`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConferenceRecord { get; set; }
#nullable restore
#else
        public string ConferenceRecord { get; set; }
#endif
        /// <summary>The URL we should call using the `conference_recording_status_callback_method` when the conference recording is available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConferenceRecordingStatusCallback { get; set; }
#nullable restore
#else
        public string ConferenceRecordingStatusCallback { get; set; }
#endif
        /// <summary>&quot;The conference recording state changes that generate a call to `conference_recording_status_callback`. Can be: `in-progress`, `completed`, `failed`, and `absent`. Separate multiple values with a space, ex: `&apos;in-progress completed failed&apos;`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ConferenceRecordingStatusCallbackEvent { get; set; }
#nullable restore
#else
        public List<string> ConferenceRecordingStatusCallbackEvent { get; set; }
#endif
        /// <summary>&quot;The HTTP method we should use to call `conference_recording_status_callback`. Can be: `GET` or `POST` and defaults to `POST`.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_ConferenceRecordingStatusCallbackMethod? ConferenceRecordingStatusCallbackMethod { get; set; }
        /// <summary>The URL we should call using the `conference_status_callback_method` when the conference events in `conference_status_callback_event` occur. Only the value set by the first participant to join the conference is used. Subsequent `conference_status_callback` values are ignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConferenceStatusCallback { get; set; }
#nullable restore
#else
        public string ConferenceStatusCallback { get; set; }
#endif
        /// <summary>&quot;The conference state changes that should generate a call to `conference_status_callback`. Can be: `start`, `end`, `join`, `leave`, `mute`, `hold`, `modify`, `speaker`, and `announcement`. Separate multiple values with a space. Defaults to `start end`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ConferenceStatusCallbackEvent { get; set; }
#nullable restore
#else
        public List<string> ConferenceStatusCallbackEvent { get; set; }
#endif
        /// <summary>&quot;The HTTP method we should use to call `conference_status_callback`. Can be: `GET` or `POST` and defaults to `POST`.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_ConferenceStatusCallbackMethod? ConferenceStatusCallbackMethod { get; set; }
        /// <summary>&quot;Whether to trim leading and trailing silence from the conference recording. Can be: `trim-silence` or `do-not-trim` and defaults to `trim-silence`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConferenceTrim { get; set; }
#nullable restore
#else
        public string ConferenceTrim { get; set; }
#endif
        /// <summary>&quot;Whether to allow an agent to hear the state of the outbound call, including ringing or disconnect messages. Can be: `true` or `false` and defaults to `true`.&quot;</summary>
        public bool? EarlyMedia { get; set; }
        /// <summary>&quot;Whether to end the conference when the participant leaves. Can be: `true` or `false` and defaults to `false`.&quot;</summary>
        public bool? EndConferenceOnExit { get; set; }
        /// <summary>The phone number, Client identifier, or username portion of SIP address that made this call. Phone numbers are in [E.164](https://www.twilio.com/docs/glossary/what-e164) format (e.g., +16175551212). Client identifiers are formatted `client:name`. If using a phone number, it must be a Twilio number or a Verified [outgoing caller id](https://www.twilio.com/docs/voice/api/outgoing-caller-ids) for your account. If the `to` parameter is a phone number, `from` must also be a phone number. If `to` is sip address, this value of `from` should be a username portion to be used to populate the P-Asserted-Identity header that is passed to the SIP endpoint.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>&quot;Jitter buffer size for the connecting participant. Twilio will use this setting to apply Jitter Buffer before participant&apos;s audio is mixed into the conference. Can be: `off`, `small`, `medium`, and `large`. Default to `large`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JitterBufferSize { get; set; }
#nullable restore
#else
        public string JitterBufferSize { get; set; }
#endif
        /// <summary>A label for this participant. If one is supplied, it may subsequently be used to fetch, update or delete the participant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>&quot;Whether to detect if a human, answering machine, or fax has picked up the call. Can be: `Enable` or `DetectMessageEnd`. Use `Enable` if you would like us to return `AnsweredBy` as soon as the called party is identified. Use `DetectMessageEnd`, if you would like to leave a message on an answering machine. For more information, see [Answering Machine Detection](https://www.twilio.com/docs/voice/answering-machine-detection).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MachineDetection { get; set; }
#nullable restore
#else
        public string MachineDetection { get; set; }
#endif
        /// <summary>&quot;The number of milliseconds of initial silence after which an `unknown` AnsweredBy result will be returned. Possible Values: 2000-10000. Default: 5000.&quot;</summary>
        public int? MachineDetectionSilenceTimeout { get; set; }
        /// <summary>&quot;The number of milliseconds of silence after speech activity at which point the speech activity is considered complete. Possible Values: 500-5000. Default: 1200.&quot;</summary>
        public int? MachineDetectionSpeechEndThreshold { get; set; }
        /// <summary>&quot;The number of milliseconds that is used as the measuring stick for the length of the speech activity, where durations lower than this value will be interpreted as a human and longer than this value as a machine. Possible Values: 1000-6000. Default: 2400.&quot;</summary>
        public int? MachineDetectionSpeechThreshold { get; set; }
        /// <summary>The number of seconds that we should attempt to detect an answering machine before timing out and sending a voice request with `AnsweredBy` of `unknown`. The default timeout is 30 seconds.</summary>
        public int? MachineDetectionTimeout { get; set; }
        /// <summary>The maximum number of participants in the conference. Can be a positive integer from `2` to `250`. The default value is `250`.</summary>
        public int? MaxParticipants { get; set; }
        /// <summary>Whether the agent is muted in the conference. Can be `true` or `false` and the default is `false`.</summary>
        public bool? Muted { get; set; }
        /// <summary>Whether to record the participant and their conferences, including the time between conferences. Can be `true` or `false` and the default is `false`.</summary>
        public bool? Record { get; set; }
        /// <summary>&quot;The recording channels for the final recording. Can be: `mono` or `dual` and the default is `mono`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordingChannels { get; set; }
#nullable restore
#else
        public string RecordingChannels { get; set; }
#endif
        /// <summary>The URL that we should call using the `recording_status_callback_method` when the recording status changes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordingStatusCallback { get; set; }
#nullable restore
#else
        public string RecordingStatusCallback { get; set; }
#endif
        /// <summary>&quot;The recording state changes that should generate a call to `recording_status_callback`. Can be: `started`, `in-progress`, `paused`, `resumed`, `stopped`, `completed`, `failed`, and `absent`. Separate multiple values with a space, ex: `&apos;in-progress completed failed&apos;`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RecordingStatusCallbackEvent { get; set; }
#nullable restore
#else
        public List<string> RecordingStatusCallbackEvent { get; set; }
#endif
        /// <summary>&quot;The HTTP method we should use when we call `recording_status_callback`. Can be: `GET` or `POST` and defaults to `POST`.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_RecordingStatusCallbackMethod? RecordingStatusCallbackMethod { get; set; }
        /// <summary>&quot;The audio track to record for the call. Can be: `inbound`, `outbound` or `both`. The default is `both`. `inbound` records the audio that is received by Twilio. `outbound` records the audio that is sent from Twilio. `both` records the audio that is received and sent by Twilio.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordingTrack { get; set; }
#nullable restore
#else
        public string RecordingTrack { get; set; }
#endif
        /// <summary>The [region](https://support.twilio.com/hc/en-us/articles/223132167-How-global-low-latency-routing-and-region-selection-work-for-conferences-and-Client-calls) where we should mix the recorded audio. Can be:`us1`, `us2`, `ie1`, `de1`, `sg1`, `br1`, `au1`, or `jp1`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The SIP password for authentication.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SipAuthPassword { get; set; }
#nullable restore
#else
        public string SipAuthPassword { get; set; }
#endif
        /// <summary>The SIP username used for authentication.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SipAuthUsername { get; set; }
#nullable restore
#else
        public string SipAuthUsername { get; set; }
#endif
        /// <summary>&quot;Whether to start the conference when the participant joins, if it has not already started. Can be: `true` or `false` and the default is `true`. If `false` and the conference has not started, the participant is muted and hears background music until another participant starts the conference.&quot;</summary>
        public bool? StartConferenceOnEnter { get; set; }
        /// <summary>The URL we should call using the `status_callback_method` to send status information to your application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusCallback { get; set; }
#nullable restore
#else
        public string StatusCallback { get; set; }
#endif
        /// <summary>&quot;The conference state changes that should generate a call to `status_callback`. Can be: `initiated`, `ringing`, `answered`, and `completed`. Separate multiple values with a space. The default value is `completed`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StatusCallbackEvent { get; set; }
#nullable restore
#else
        public List<string> StatusCallbackEvent { get; set; }
#endif
        /// <summary>&quot;The HTTP method we should use to call `status_callback`. Can be: `GET` and `POST` and defaults to `POST`.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_StatusCallbackMethod? StatusCallbackMethod { get; set; }
        /// <summary>The maximum duration of the call in seconds. Constraints depend on account and configuration.</summary>
        public int? TimeLimit { get; set; }
        /// <summary>The number of seconds that we should allow the phone to ring before assuming there is no answer. Can be an integer between `5` and `600`, inclusive. The default value is `60`. We always add a 5-second timeout buffer to outgoing calls, so  value of 10 would result in an actual timeout that was closer to 15 seconds.</summary>
        public int? Timeout { get; set; }
        /// <summary>The phone number, SIP address, Client, TwiML App identifier that received this call. Phone numbers are in [E.164](https://www.twilio.com/docs/glossary/what-e164) format (e.g., +16175551212). SIP addresses are formatted as `sip:name@company.com`. Client identifiers are formatted `client:name`. TwiML App identifiers are formatted `app:&lt;APP_SID&gt;`. [Custom parameters](https://www.twilio.com/docs/voice/api/conference-participant-resource#custom-parameters) may also be specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? To { get; set; }
#nullable restore
#else
        public string To { get; set; }
#endif
        /// <summary>&quot;Whether to trim any leading and trailing silence from the participant recording. Can be: `trim-silence` or `do-not-trim` and the default is `trim-silence`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Trim { get; set; }
#nullable restore
#else
        public string Trim { get; set; }
#endif
        /// <summary>The HTTP method we should use to call `wait_url`. Can be `GET` or `POST` and the default is `POST`. When using a static audio file, this should be `GET` so that we can cache the file.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_WaitMethod? WaitMethod { get; set; }
        /// <summary>The URL that Twilio calls using the `wait_method` before the conference has started. The URL may return an MP3 file, a WAV file, or a TwiML document. The default value is the URL of our standard hold music. If you do not want anything to play while waiting for the conference to start, specify an empty string by setting `wait_url` to `&apos;&apos;`. For more details on the allowable verbs within the `waitUrl`, see the `waitUrl` attribute in the [&lt;Conference&gt; TwiML instruction](https://www.twilio.com/docs/voice/twiml/conference#attributes-waiturl).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WaitUrl { get; set; }
#nullable restore
#else
        public string WaitUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant"/> and sets the default values.
        /// </summary>
        public Twilio_api_v2010_CreateParticipant()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AmdStatusCallback", n => { AmdStatusCallback = n.GetStringValue(); } },
                { "AmdStatusCallbackMethod", n => { AmdStatusCallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_AmdStatusCallbackMethod>(); } },
                { "Beep", n => { Beep = n.GetStringValue(); } },
                { "Byoc", n => { Byoc = n.GetStringValue(); } },
                { "CallReason", n => { CallReason = n.GetStringValue(); } },
                { "CallSidToCoach", n => { CallSidToCoach = n.GetStringValue(); } },
                { "CallToken", n => { CallToken = n.GetStringValue(); } },
                { "CallerDisplayName", n => { CallerDisplayName = n.GetStringValue(); } },
                { "CallerId", n => { CallerId = n.GetStringValue(); } },
                { "ClientNotificationUrl", n => { ClientNotificationUrl = n.GetStringValue(); } },
                { "Coaching", n => { Coaching = n.GetBoolValue(); } },
                { "ConferenceRecord", n => { ConferenceRecord = n.GetStringValue(); } },
                { "ConferenceRecordingStatusCallback", n => { ConferenceRecordingStatusCallback = n.GetStringValue(); } },
                { "ConferenceRecordingStatusCallbackEvent", n => { ConferenceRecordingStatusCallbackEvent = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ConferenceRecordingStatusCallbackMethod", n => { ConferenceRecordingStatusCallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_ConferenceRecordingStatusCallbackMethod>(); } },
                { "ConferenceStatusCallback", n => { ConferenceStatusCallback = n.GetStringValue(); } },
                { "ConferenceStatusCallbackEvent", n => { ConferenceStatusCallbackEvent = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ConferenceStatusCallbackMethod", n => { ConferenceStatusCallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_ConferenceStatusCallbackMethod>(); } },
                { "ConferenceTrim", n => { ConferenceTrim = n.GetStringValue(); } },
                { "EarlyMedia", n => { EarlyMedia = n.GetBoolValue(); } },
                { "EndConferenceOnExit", n => { EndConferenceOnExit = n.GetBoolValue(); } },
                { "From", n => { From = n.GetStringValue(); } },
                { "JitterBufferSize", n => { JitterBufferSize = n.GetStringValue(); } },
                { "Label", n => { Label = n.GetStringValue(); } },
                { "MachineDetection", n => { MachineDetection = n.GetStringValue(); } },
                { "MachineDetectionSilenceTimeout", n => { MachineDetectionSilenceTimeout = n.GetIntValue(); } },
                { "MachineDetectionSpeechEndThreshold", n => { MachineDetectionSpeechEndThreshold = n.GetIntValue(); } },
                { "MachineDetectionSpeechThreshold", n => { MachineDetectionSpeechThreshold = n.GetIntValue(); } },
                { "MachineDetectionTimeout", n => { MachineDetectionTimeout = n.GetIntValue(); } },
                { "MaxParticipants", n => { MaxParticipants = n.GetIntValue(); } },
                { "Muted", n => { Muted = n.GetBoolValue(); } },
                { "Record", n => { Record = n.GetBoolValue(); } },
                { "RecordingChannels", n => { RecordingChannels = n.GetStringValue(); } },
                { "RecordingStatusCallback", n => { RecordingStatusCallback = n.GetStringValue(); } },
                { "RecordingStatusCallbackEvent", n => { RecordingStatusCallbackEvent = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "RecordingStatusCallbackMethod", n => { RecordingStatusCallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_RecordingStatusCallbackMethod>(); } },
                { "RecordingTrack", n => { RecordingTrack = n.GetStringValue(); } },
                { "Region", n => { Region = n.GetStringValue(); } },
                { "SipAuthPassword", n => { SipAuthPassword = n.GetStringValue(); } },
                { "SipAuthUsername", n => { SipAuthUsername = n.GetStringValue(); } },
                { "StartConferenceOnEnter", n => { StartConferenceOnEnter = n.GetBoolValue(); } },
                { "StatusCallback", n => { StatusCallback = n.GetStringValue(); } },
                { "StatusCallbackEvent", n => { StatusCallbackEvent = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "StatusCallbackMethod", n => { StatusCallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_StatusCallbackMethod>(); } },
                { "TimeLimit", n => { TimeLimit = n.GetIntValue(); } },
                { "Timeout", n => { Timeout = n.GetIntValue(); } },
                { "To", n => { To = n.GetStringValue(); } },
                { "Trim", n => { Trim = n.GetStringValue(); } },
                { "WaitMethod", n => { WaitMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_WaitMethod>(); } },
                { "WaitUrl", n => { WaitUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AmdStatusCallback", AmdStatusCallback);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_AmdStatusCallbackMethod>("AmdStatusCallbackMethod", AmdStatusCallbackMethod);
            writer.WriteStringValue("Beep", Beep);
            writer.WriteStringValue("Byoc", Byoc);
            writer.WriteStringValue("CallerDisplayName", CallerDisplayName);
            writer.WriteStringValue("CallerId", CallerId);
            writer.WriteStringValue("CallReason", CallReason);
            writer.WriteStringValue("CallSidToCoach", CallSidToCoach);
            writer.WriteStringValue("CallToken", CallToken);
            writer.WriteStringValue("ClientNotificationUrl", ClientNotificationUrl);
            writer.WriteBoolValue("Coaching", Coaching);
            writer.WriteStringValue("ConferenceRecord", ConferenceRecord);
            writer.WriteStringValue("ConferenceRecordingStatusCallback", ConferenceRecordingStatusCallback);
            writer.WriteCollectionOfPrimitiveValues<string>("ConferenceRecordingStatusCallbackEvent", ConferenceRecordingStatusCallbackEvent);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_ConferenceRecordingStatusCallbackMethod>("ConferenceRecordingStatusCallbackMethod", ConferenceRecordingStatusCallbackMethod);
            writer.WriteStringValue("ConferenceStatusCallback", ConferenceStatusCallback);
            writer.WriteCollectionOfPrimitiveValues<string>("ConferenceStatusCallbackEvent", ConferenceStatusCallbackEvent);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_ConferenceStatusCallbackMethod>("ConferenceStatusCallbackMethod", ConferenceStatusCallbackMethod);
            writer.WriteStringValue("ConferenceTrim", ConferenceTrim);
            writer.WriteBoolValue("EarlyMedia", EarlyMedia);
            writer.WriteBoolValue("EndConferenceOnExit", EndConferenceOnExit);
            writer.WriteStringValue("From", From);
            writer.WriteStringValue("JitterBufferSize", JitterBufferSize);
            writer.WriteStringValue("Label", Label);
            writer.WriteStringValue("MachineDetection", MachineDetection);
            writer.WriteIntValue("MachineDetectionSilenceTimeout", MachineDetectionSilenceTimeout);
            writer.WriteIntValue("MachineDetectionSpeechEndThreshold", MachineDetectionSpeechEndThreshold);
            writer.WriteIntValue("MachineDetectionSpeechThreshold", MachineDetectionSpeechThreshold);
            writer.WriteIntValue("MachineDetectionTimeout", MachineDetectionTimeout);
            writer.WriteIntValue("MaxParticipants", MaxParticipants);
            writer.WriteBoolValue("Muted", Muted);
            writer.WriteBoolValue("Record", Record);
            writer.WriteStringValue("RecordingChannels", RecordingChannels);
            writer.WriteStringValue("RecordingStatusCallback", RecordingStatusCallback);
            writer.WriteCollectionOfPrimitiveValues<string>("RecordingStatusCallbackEvent", RecordingStatusCallbackEvent);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_RecordingStatusCallbackMethod>("RecordingStatusCallbackMethod", RecordingStatusCallbackMethod);
            writer.WriteStringValue("RecordingTrack", RecordingTrack);
            writer.WriteStringValue("Region", Region);
            writer.WriteStringValue("SipAuthPassword", SipAuthPassword);
            writer.WriteStringValue("SipAuthUsername", SipAuthUsername);
            writer.WriteBoolValue("StartConferenceOnEnter", StartConferenceOnEnter);
            writer.WriteStringValue("StatusCallback", StatusCallback);
            writer.WriteCollectionOfPrimitiveValues<string>("StatusCallbackEvent", StatusCallbackEvent);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_StatusCallbackMethod>("StatusCallbackMethod", StatusCallbackMethod);
            writer.WriteIntValue("TimeLimit", TimeLimit);
            writer.WriteIntValue("Timeout", Timeout);
            writer.WriteStringValue("To", To);
            writer.WriteStringValue("Trim", Trim);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreateParticipant_WaitMethod>("WaitMethod", WaitMethod);
            writer.WriteStringValue("WaitUrl", WaitUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
