// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Twilio_preview_UpdateWirelessSim : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The CallbackMethod property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackMethod { get; set; }
#nullable restore
#else
        public string CallbackMethod { get; set; }
#endif
        /// <summary>The CallbackUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackUrl { get; set; }
#nullable restore
#else
        public string CallbackUrl { get; set; }
#endif
        /// <summary>The CommandsCallbackMethod property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_CommandsCallbackMethod? CommandsCallbackMethod { get; set; }
        /// <summary>The CommandsCallbackUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommandsCallbackUrl { get; set; }
#nullable restore
#else
        public string CommandsCallbackUrl { get; set; }
#endif
        /// <summary>The FriendlyName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>The RatePlan property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RatePlan { get; set; }
#nullable restore
#else
        public string RatePlan { get; set; }
#endif
        /// <summary>The SmsFallbackMethod property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_SmsFallbackMethod? SmsFallbackMethod { get; set; }
        /// <summary>The SmsFallbackUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmsFallbackUrl { get; set; }
#nullable restore
#else
        public string SmsFallbackUrl { get; set; }
#endif
        /// <summary>The SmsMethod property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_SmsMethod? SmsMethod { get; set; }
        /// <summary>The SmsUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmsUrl { get; set; }
#nullable restore
#else
        public string SmsUrl { get; set; }
#endif
        /// <summary>The Status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The UniqueName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UniqueName { get; set; }
#nullable restore
#else
        public string UniqueName { get; set; }
#endif
        /// <summary>The VoiceFallbackMethod property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_VoiceFallbackMethod? VoiceFallbackMethod { get; set; }
        /// <summary>The VoiceFallbackUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoiceFallbackUrl { get; set; }
#nullable restore
#else
        public string VoiceFallbackUrl { get; set; }
#endif
        /// <summary>The VoiceMethod property</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_VoiceMethod? VoiceMethod { get; set; }
        /// <summary>The VoiceUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoiceUrl { get; set; }
#nullable restore
#else
        public string VoiceUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim"/> and sets the default values.
        /// </summary>
        public Twilio_preview_UpdateWirelessSim()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CallbackMethod", n => { CallbackMethod = n.GetStringValue(); } },
                { "CallbackUrl", n => { CallbackUrl = n.GetStringValue(); } },
                { "CommandsCallbackMethod", n => { CommandsCallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_CommandsCallbackMethod>(); } },
                { "CommandsCallbackUrl", n => { CommandsCallbackUrl = n.GetStringValue(); } },
                { "FriendlyName", n => { FriendlyName = n.GetStringValue(); } },
                { "RatePlan", n => { RatePlan = n.GetStringValue(); } },
                { "SmsFallbackMethod", n => { SmsFallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_SmsFallbackMethod>(); } },
                { "SmsFallbackUrl", n => { SmsFallbackUrl = n.GetStringValue(); } },
                { "SmsMethod", n => { SmsMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_SmsMethod>(); } },
                { "SmsUrl", n => { SmsUrl = n.GetStringValue(); } },
                { "Status", n => { Status = n.GetStringValue(); } },
                { "UniqueName", n => { UniqueName = n.GetStringValue(); } },
                { "VoiceFallbackMethod", n => { VoiceFallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_VoiceFallbackMethod>(); } },
                { "VoiceFallbackUrl", n => { VoiceFallbackUrl = n.GetStringValue(); } },
                { "VoiceMethod", n => { VoiceMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_VoiceMethod>(); } },
                { "VoiceUrl", n => { VoiceUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("CallbackMethod", CallbackMethod);
            writer.WriteStringValue("CallbackUrl", CallbackUrl);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_CommandsCallbackMethod>("CommandsCallbackMethod", CommandsCallbackMethod);
            writer.WriteStringValue("CommandsCallbackUrl", CommandsCallbackUrl);
            writer.WriteStringValue("FriendlyName", FriendlyName);
            writer.WriteStringValue("RatePlan", RatePlan);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_SmsFallbackMethod>("SmsFallbackMethod", SmsFallbackMethod);
            writer.WriteStringValue("SmsFallbackUrl", SmsFallbackUrl);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_SmsMethod>("SmsMethod", SmsMethod);
            writer.WriteStringValue("SmsUrl", SmsUrl);
            writer.WriteStringValue("Status", Status);
            writer.WriteStringValue("UniqueName", UniqueName);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_VoiceFallbackMethod>("VoiceFallbackMethod", VoiceFallbackMethod);
            writer.WriteStringValue("VoiceFallbackUrl", VoiceFallbackUrl);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_preview_UpdateWirelessSim_VoiceMethod>("VoiceMethod", VoiceMethod);
            writer.WriteStringValue("VoiceUrl", VoiceUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
