// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>
    /// Full configuration settings for this Conversation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TwilioConversationsV2PatchConversationById200ResponseConfiguration : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Channel-specific parameters forwarded as-is to the downstream sending service.Allows passing backend-specific fields without requiring API changes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfigurationChannelSettings? ChannelSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfigurationChannelSettings ChannelSettings { get; set; }
#endif
        /// <summary>&quot;Type of Conversation grouping strategy:- `GROUP_BY_PROFILE`: Groups Communications by resolved Profile from the Memory Store.  A Profile is looked up or created for `CUSTOMER` Participant types. All Communications from the same Profile are in the same Conversation, regardless of address or channel.- `GROUP_BY_PARTICIPANT_ADDRESSES`: Groups Communications by Participant addresses across all channels.  A customer using +18005550100 will be in the same Conversation whether they contact by SMS, WhatsApp, or RCS.- `GROUP_BY_PARTICIPANT_ADDRESSES_AND_CHANNEL_TYPE`: Groups Communications by both Participant addresses AND channel.  A customer using +18005550100 by SMS will be in a different Conversation than the same customer by Voice.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfigurationConversationGroupingType? ConversationGroupingType { get; set; }
        /// <summary>Configuration for Conversations V1 bridge. When set, messaging channels route through Conversations V1. Use this to integrate with existing Conversations V1 applications.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ConversationsV1Bridge? ConversationsV1Bridge { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ConversationsV1Bridge ConversationsV1Bridge { get; set; }
#endif
        /// <summary>Human-readable description for the Configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>A human-readable name for the configuration. Limited to 32 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>List of Intelligence Configuration IDs configured for this Configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IntelligenceConfigurationIds { get; set; }
#nullable restore
#else
        public List<string> IntelligenceConfigurationIds { get; set; }
#endif
        /// <summary>Whether memory extraction is enabled for conversations under this configuration. Defaults to false.</summary>
        public bool? MemoryExtractionEnabled { get; set; }
        /// <summary>Memory Store ID for Profile resolution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemoryStoreId { get; set; }
#nullable restore
#else
        public string MemoryStoreId { get; set; }
#endif
        /// <summary>List of default webhook configurations applied to Conversations under this Configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2StatusCallbackConfig>? StatusCallbacks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2StatusCallbackConfig> StatusCallbacks { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfiguration"/> and sets the default values.
        /// </summary>
        public TwilioConversationsV2PatchConversationById200ResponseConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
            MemoryExtractionEnabled = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channelSettings", n => { ChannelSettings = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfigurationChannelSettings>(global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfigurationChannelSettings.CreateFromDiscriminatorValue); } },
                { "conversationGroupingType", n => { ConversationGroupingType = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfigurationConversationGroupingType>(); } },
                { "conversationsV1Bridge", n => { ConversationsV1Bridge = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ConversationsV1Bridge>(global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ConversationsV1Bridge.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "intelligenceConfigurationIds", n => { IntelligenceConfigurationIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "memoryExtractionEnabled", n => { MemoryExtractionEnabled = n.GetBoolValue(); } },
                { "memoryStoreId", n => { MemoryStoreId = n.GetStringValue(); } },
                { "statusCallbacks", n => { StatusCallbacks = n.GetCollectionOfObjectValues<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2StatusCallbackConfig>(global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2StatusCallbackConfig.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfigurationChannelSettings>("channelSettings", ChannelSettings);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioConversationsV2PatchConversationById200ResponseConfigurationConversationGroupingType>("conversationGroupingType", ConversationGroupingType);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2ConversationsV1Bridge>("conversationsV1Bridge", ConversationsV1Bridge);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteCollectionOfPrimitiveValues<string>("intelligenceConfigurationIds", IntelligenceConfigurationIds);
            writer.WriteBoolValue("memoryExtractionEnabled", MemoryExtractionEnabled);
            writer.WriteStringValue("memoryStoreId", MemoryStoreId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Twilio.OpenApiClient.Models.ConversationsV2StatusCallbackConfig>("statusCallbacks", StatusCallbacks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
