// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TwilioVerifyV2CreateNewFactorPasskey201Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The unique SID identifier of the Account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSid { get; set; }
#nullable restore
#else
        public string AccountSid { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Contains the `factor_type` specific secret and metadata. The Binding property is ONLY returned upon Factor creation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseBinding? Binding { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseBinding Binding { get; set; }
#endif
        /// <summary>An object that contains configurations specific to a `factor_type`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseConfig? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseConfig Config { get; set; }
#endif
        /// <summary>The date that this Factor was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date that this Factor was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The unique SID identifier of the Entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntitySid { get; set; }
#nullable restore
#else
        public string EntitySid { get; set; }
#endif
        /// <summary>The Type of this Factor. Currently `push` and `totp` are supported.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseFactorType? FactorType { get; set; }
        /// <summary>The friendly name of this Factor. This can be any string up to 64 characters, meant for humans to distinguish between Factors.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>Customer unique identity for the Entity owner of the Factor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Identity { get; set; }
#nullable restore
#else
        public string Identity { get; set; }
#endif
        /// <summary>Custom metadata associated with the factor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseMetadata Metadata { get; set; }
#endif
        /// <summary>The options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseOptions? Options { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseOptions Options { get; set; }
#endif
        /// <summary>The unique SID identifier of the Service.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceSid { get; set; }
#nullable restore
#else
        public string ServiceSid { get; set; }
#endif
        /// <summary>A 34 character string that uniquely identifies this Factor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sid { get; set; }
#nullable restore
#else
        public string Sid { get; set; }
#endif
        /// <summary>The Status of this Factor. One of `unverified` or `verified`.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseStatus? Status { get; set; }
        /// <summary>The URL of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201Response"/> and sets the default values.
        /// </summary>
        public TwilioVerifyV2CreateNewFactorPasskey201Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_sid", n => { AccountSid = n.GetStringValue(); } },
                { "binding", n => { Binding = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseBinding>(global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseBinding.CreateFromDiscriminatorValue); } },
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseConfig>(global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseConfig.CreateFromDiscriminatorValue); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "entity_sid", n => { EntitySid = n.GetStringValue(); } },
                { "factor_type", n => { FactorType = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseFactorType>(); } },
                { "friendly_name", n => { FriendlyName = n.GetStringValue(); } },
                { "identity", n => { Identity = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseMetadata>(global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseMetadata.CreateFromDiscriminatorValue); } },
                { "options", n => { Options = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseOptions>(global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseOptions.CreateFromDiscriminatorValue); } },
                { "service_sid", n => { ServiceSid = n.GetStringValue(); } },
                { "sid", n => { Sid = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseStatus>(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_sid", AccountSid);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseBinding>("binding", Binding);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseConfig>("config", Config);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteStringValue("entity_sid", EntitySid);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseFactorType>("factor_type", FactorType);
            writer.WriteStringValue("friendly_name", FriendlyName);
            writer.WriteStringValue("identity", Identity);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseMetadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseOptions>("options", Options);
            writer.WriteStringValue("service_sid", ServiceSid);
            writer.WriteStringValue("sid", Sid);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.TwilioVerifyV2CreateNewFactorPasskey201ResponseStatus>("status", Status);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
