// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Twilio_api_v2010_CreatePayments : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Type of bank account if payment source is ACH. One of `consumer-checking`, `consumer-savings`, or `commercial-checking`. The default value is `consumer-checking`.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Payments_enum_bank_account_type? BankAccountType { get; set; }
        /// <summary>A positive decimal value less than 1,000,000 to charge against the credit card or bank account. Default currency can be overwritten with `currency` field. Leave blank or set to 0 to tokenize.</summary>
        public double? ChargeAmount { get; set; }
        /// <summary>Whether to prompt the caller to confirm their payment information before submitting to the payment gateway. If `true`, the caller will hear the last 4 digits of their card or account number and must press 1 to confirm or 2 to cancel. Default is `false`.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments_Confirmation? Confirmation { get; set; }
        /// <summary>The currency of the `charge_amount`, formatted as [ISO 4127](http://www.iso.org/iso/home/standards/currency_codes.htm) format. The default value is `USD` and all values allowed from the Pay Connector are accepted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The description can be used to provide more details regarding the transaction. This information is submitted along with the payment details to the Payment Connector which are then posted on the transactions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>A unique token that will be used to ensure that multiple API calls with the same information do not result in multiple transactions. This should be a unique string value per API call and can be a randomly generated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdempotencyKey { get; set; }
#nullable restore
#else
        public string IdempotencyKey { get; set; }
#endif
        /// <summary>A list of inputs that should be accepted. Currently only `dtmf` is supported. All digits captured during a pay session are redacted from the logs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Input { get; set; }
#nullable restore
#else
        public string Input { get; set; }
#endif
        /// <summary>A positive integer that is used to validate the length of the `PostalCode` inputted by the user. User must enter this many digits.</summary>
        public int? MinPostalCodeLength { get; set; }
        /// <summary>A single-level JSON object used to pass custom parameters to payment processors. (Required for ACH payments). The information that has to be included here depends on the &lt;Pay&gt; Connector. [Read more](https://www.twilio.com/console/voice/pay-connectors).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments_Parameter? Parameter { get; set; }
#nullable restore
#else
        public global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments_Parameter Parameter { get; set; }
#endif
        /// <summary>This is the unique name corresponding to the Pay Connector installed in the Twilio Add-ons. Learn more about [&lt;Pay&gt; Connectors](https://www.twilio.com/console/voice/pay-connectors). The default value is `Default`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentConnector { get; set; }
#nullable restore
#else
        public string PaymentConnector { get; set; }
#endif
        /// <summary>Type of payment being captured. One of `credit-card` or `ach-debit`. The default value is `credit-card`.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Payments_enum_payment_method? PaymentMethod { get; set; }
        /// <summary>Indicates whether the credit card postal code (zip code) is a required piece of payment information that must be provided by the caller. The default is `true`.</summary>
        public bool? PostalCode { get; set; }
        /// <summary>A comma-separated list of payment information fields that require the caller to enter the same value twice for confirmation. Supported values are `payment-card-number`, `expiration-date`, `security-code`, and `postal-code`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequireMatchingInputs { get; set; }
#nullable restore
#else
        public string RequireMatchingInputs { get; set; }
#endif
        /// <summary>Indicates whether the credit card security code is a required piece of payment information that must be provided by the caller. The default is `true`.</summary>
        public bool? SecurityCode { get; set; }
        /// <summary>Provide an absolute or relative URL to receive status updates regarding your Pay session. Read more about the [expected StatusCallback values](https://www.twilio.com/docs/voice/api/payment-resource#statuscallback)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusCallback { get; set; }
#nullable restore
#else
        public string StatusCallback { get; set; }
#endif
        /// <summary>The number of seconds that &lt;Pay&gt; should wait for the caller to press a digit between each subsequent digit, after the first one, before moving on to validate the digits captured. The default is `5`, maximum is `600`.</summary>
        public int? Timeout { get; set; }
        /// <summary>Indicates whether the payment method should be tokenized as a `one-time`, `reusable`, or `payment-method` token. The default value is `reusable`. Do not enter a charge amount when tokenizing. If a charge amount is entered, the payment method will be charged and not tokenized.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Payments_enum_token_type? TokenType { get; set; }
        /// <summary>Credit card types separated by space that Pay should accept. The default value is `visa mastercard amex`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ValidCardTypes { get; set; }
#nullable restore
#else
        public string ValidCardTypes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments"/> and sets the default values.
        /// </summary>
        public Twilio_api_v2010_CreatePayments()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "BankAccountType", n => { BankAccountType = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Payments_enum_bank_account_type>(); } },
                { "ChargeAmount", n => { ChargeAmount = n.GetDoubleValue(); } },
                { "Confirmation", n => { Confirmation = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments_Confirmation>(); } },
                { "Currency", n => { Currency = n.GetStringValue(); } },
                { "Description", n => { Description = n.GetStringValue(); } },
                { "IdempotencyKey", n => { IdempotencyKey = n.GetStringValue(); } },
                { "Input", n => { Input = n.GetStringValue(); } },
                { "MinPostalCodeLength", n => { MinPostalCodeLength = n.GetIntValue(); } },
                { "Parameter", n => { Parameter = n.GetObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments_Parameter>(global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments_Parameter.CreateFromDiscriminatorValue); } },
                { "PaymentConnector", n => { PaymentConnector = n.GetStringValue(); } },
                { "PaymentMethod", n => { PaymentMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Payments_enum_payment_method>(); } },
                { "PostalCode", n => { PostalCode = n.GetBoolValue(); } },
                { "RequireMatchingInputs", n => { RequireMatchingInputs = n.GetStringValue(); } },
                { "SecurityCode", n => { SecurityCode = n.GetBoolValue(); } },
                { "StatusCallback", n => { StatusCallback = n.GetStringValue(); } },
                { "Timeout", n => { Timeout = n.GetIntValue(); } },
                { "TokenType", n => { TokenType = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Payments_enum_token_type>(); } },
                { "ValidCardTypes", n => { ValidCardTypes = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Payments_enum_bank_account_type>("BankAccountType", BankAccountType);
            writer.WriteDoubleValue("ChargeAmount", ChargeAmount);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments_Confirmation>("Confirmation", Confirmation);
            writer.WriteStringValue("Currency", Currency);
            writer.WriteStringValue("Description", Description);
            writer.WriteStringValue("IdempotencyKey", IdempotencyKey);
            writer.WriteStringValue("Input", Input);
            writer.WriteIntValue("MinPostalCodeLength", MinPostalCodeLength);
            writer.WriteObjectValue<global::Soenneker.Twilio.OpenApiClient.Models.Twilio_api_v2010_CreatePayments_Parameter>("Parameter", Parameter);
            writer.WriteStringValue("PaymentConnector", PaymentConnector);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Payments_enum_payment_method>("PaymentMethod", PaymentMethod);
            writer.WriteBoolValue("PostalCode", PostalCode);
            writer.WriteStringValue("RequireMatchingInputs", RequireMatchingInputs);
            writer.WriteBoolValue("SecurityCode", SecurityCode);
            writer.WriteStringValue("StatusCallback", StatusCallback);
            writer.WriteIntValue("Timeout", Timeout);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Payments_enum_token_type>("TokenType", TokenType);
            writer.WriteStringValue("ValidCardTypes", ValidCardTypes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
