// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TwilioConversationsV2CreateCommunicationInConversation_contentMember2_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TRANSCRIPTION")]
        #pragma warning disable CS1591
        TRANSCRIPTION,
        #pragma warning restore CS1591
    }
}
