// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>Dimension over which to aggregate usage records. Can be: `sim`, `fleet`, `network`, `isoCountry`. Default is to not aggregate across any of these dimensions, UsageRecords will be aggregated into the time buckets described by the `Granularity` parameter.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UsageRecordEnumGroup
    {
        [EnumMember(Value = "sim")]
        #pragma warning disable CS1591
        Sim,
        #pragma warning restore CS1591
        [EnumMember(Value = "fleet")]
        #pragma warning disable CS1591
        Fleet,
        #pragma warning restore CS1591
        [EnumMember(Value = "network")]
        #pragma warning disable CS1591
        Network,
        #pragma warning restore CS1591
        [EnumMember(Value = "isoCountry")]
        #pragma warning disable CS1591
        IsoCountry,
        #pragma warning restore CS1591
    }
}
