// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>The Notification Level of this User Conversation. One of `default` or `muted`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum User_conversation_enum_notification_level
    {
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        Default,
        #pragma warning restore CS1591
        [EnumMember(Value = "muted")]
        #pragma warning disable CS1591
        Muted,
        #pragma warning restore CS1591
    }
}
