// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Voice_v1_byoc_trunk : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the BYOC Trunk resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSid { get; set; }
#nullable restore
#else
        public string AccountSid { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether Caller ID Name (CNAM) lookup is enabled for the trunk. If enabled, all inbound calls to the BYOC Trunk from the United States and Canada automatically perform a CNAM Lookup and display Caller ID data on your phone. See [CNAM Lookups](https://www.twilio.com/docs/sip-trunking#CNAM) for more information.</summary>
        public bool? CnamLookupEnabled { get; set; }
        /// <summary>The SID of the Connection Policy that Twilio will use when routing traffic to your communications infrastructure.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionPolicySid { get; set; }
#nullable restore
#else
        public string ConnectionPolicySid { get; set; }
#endif
        /// <summary>The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.</summary>
        public DateTimeOffset? DateUpdated { get; set; }
        /// <summary>The string that you assigned to describe the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyName { get; set; }
#nullable restore
#else
        public string FriendlyName { get; set; }
#endif
        /// <summary>The SID of the SIP Domain that should be used in the `From` header of originating calls sent to your SIP infrastructure. If your SIP infrastructure allows users to &quot;call back&quot; an incoming call, configure this with a [SIP Domain](https://www.twilio.com/docs/voice/api/sending-sip) to ensure proper routing. If not configured, the from domain will default to &quot;sip.twilio.com&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromDomainSid { get; set; }
#nullable restore
#else
        public string FromDomainSid { get; set; }
#endif
        /// <summary>The unique string that that we created to identify the BYOC Trunk resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sid { get; set; }
#nullable restore
#else
        public string Sid { get; set; }
#endif
        /// <summary>The HTTP method we use to call `status_callback_url`. Either `GET` or `POST`.</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk_status_callback_method? StatusCallbackMethod { get; set; }
        /// <summary>The URL that we call to pass status parameters (such as call ended) to your application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusCallbackUrl { get; set; }
#nullable restore
#else
        public string StatusCallbackUrl { get; set; }
#endif
        /// <summary>The absolute URL of the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>&quot;The HTTP method we use to call `voice_fallback_url`. Can be: `GET` or `POST`.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk_voice_fallback_method? VoiceFallbackMethod { get; set; }
        /// <summary>The URL that we call when an error occurs while retrieving or executing the TwiML requested from `voice_url`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoiceFallbackUrl { get; set; }
#nullable restore
#else
        public string VoiceFallbackUrl { get; set; }
#endif
        /// <summary>&quot;The HTTP method we use to call `voice_url`. Can be: `GET` or `POST`.&quot;</summary>
        public global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk_voice_method? VoiceMethod { get; set; }
        /// <summary>The URL we call using the `voice_method` when the BYOC Trunk receives a call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoiceUrl { get; set; }
#nullable restore
#else
        public string VoiceUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk"/> and sets the default values.
        /// </summary>
        public Voice_v1_byoc_trunk()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_sid", n => { AccountSid = n.GetStringValue(); } },
                { "cnam_lookup_enabled", n => { CnamLookupEnabled = n.GetBoolValue(); } },
                { "connection_policy_sid", n => { ConnectionPolicySid = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "date_updated", n => { DateUpdated = n.GetDateTimeOffsetValue(); } },
                { "friendly_name", n => { FriendlyName = n.GetStringValue(); } },
                { "from_domain_sid", n => { FromDomainSid = n.GetStringValue(); } },
                { "sid", n => { Sid = n.GetStringValue(); } },
                { "status_callback_method", n => { StatusCallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk_status_callback_method>(); } },
                { "status_callback_url", n => { StatusCallbackUrl = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "voice_fallback_method", n => { VoiceFallbackMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk_voice_fallback_method>(); } },
                { "voice_fallback_url", n => { VoiceFallbackUrl = n.GetStringValue(); } },
                { "voice_method", n => { VoiceMethod = n.GetEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk_voice_method>(); } },
                { "voice_url", n => { VoiceUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_sid", AccountSid);
            writer.WriteBoolValue("cnam_lookup_enabled", CnamLookupEnabled);
            writer.WriteStringValue("connection_policy_sid", ConnectionPolicySid);
            writer.WriteDateTimeOffsetValue("date_created", DateCreated);
            writer.WriteDateTimeOffsetValue("date_updated", DateUpdated);
            writer.WriteStringValue("friendly_name", FriendlyName);
            writer.WriteStringValue("from_domain_sid", FromDomainSid);
            writer.WriteStringValue("sid", Sid);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk_status_callback_method>("status_callback_method", StatusCallbackMethod);
            writer.WriteStringValue("status_callback_url", StatusCallbackUrl);
            writer.WriteStringValue("url", Url);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk_voice_fallback_method>("voice_fallback_method", VoiceFallbackMethod);
            writer.WriteStringValue("voice_fallback_url", VoiceFallbackUrl);
            writer.WriteEnumValue<global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_byoc_trunk_voice_method>("voice_method", VoiceMethod);
            writer.WriteStringValue("voice_url", VoiceUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
