// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Voice_v1_dialing_permissions_dialing_permissions_country_bulk_update : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of countries updated</summary>
        public int? UpdateCount { get; set; }
        /// <summary>&quot;A bulk update request to change voice dialing country permissions stored as a URL-encoded, JSON array of update objects. For example : `[ { \&quot;iso_code\&quot;: \&quot;GB\&quot;, \&quot;low_risk_numbers_enabled\&quot;: \&quot;true\&quot;, \&quot;high_risk_special_numbers_enabled\&quot;:\&quot;true\&quot;, \&quot;high_risk_tollfraud_numbers_enabled\&quot;: \&quot;false\&quot; } ]`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateRequest { get; set; }
#nullable restore
#else
        public string UpdateRequest { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_dialing_permissions_dialing_permissions_country_bulk_update"/> and sets the default values.
        /// </summary>
        public Voice_v1_dialing_permissions_dialing_permissions_country_bulk_update()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_dialing_permissions_dialing_permissions_country_bulk_update"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_dialing_permissions_dialing_permissions_country_bulk_update CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Twilio.OpenApiClient.Models.Voice_v1_dialing_permissions_dialing_permissions_country_bulk_update();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "update_count", n => { UpdateCount = n.GetIntValue(); } },
                { "update_request", n => { UpdateRequest = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("update_count", UpdateCount);
            writer.WriteStringValue("update_request", UpdateRequest);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
