// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Twilio.OpenApiClient.Models
{
    /// <summary>Deprecated.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Wireless_v1_sim_sms_method
    {
        [EnumMember(Value = "GET")]
        #pragma warning disable CS1591
        GET,
        #pragma warning restore CS1591
        [EnumMember(Value = "POST")]
        #pragma warning disable CS1591
        POST,
        #pragma warning restore CS1591
    }
}
